__name__ = "vortex_api"
__description__ = "Vortex APIs to place orders in Rupeezy application"
__url__ = "https://vortex.rupeezy.in"
__download_url__ = "https://github.com/RupeezyTech/pyvortex"
__version__ = "2.0.2"
__author__ = "Astha Credit & Securities Pvt Ltd."
__author_email__ = "tech@rupeezy.in"
__license__ = "MIT"