# Generated by Django 4.2.20 on 2025-06-28 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0112_fix_project_name_uniqueness"),
        ("NEMO_stockroom", "0004_alter_consumablerequest_date_deleted"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ConsumableThumbnail",
            new_name="ConsumableDetails",
        ),
        migrations.AlterField(
            model_name="consumabledetails",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="stockroom_thumbnails/"),
        ),
        migrations.AddField(
            model_name="consumabledetails",
            name="warning_message",
            field=models.TextField(
                blank=True,
                help_text="The warning message to show users when they are ordering this item. HTML is NOT allowed.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="consumabledetails",
            name="image",
            field=models.ImageField(
                blank=True, help_text="The thumbnail image for this item", null=True, upload_to="stockroom_thumbnails/"
            ),
        ),
        migrations.AlterModelOptions(
            name="consumabledetails",
            options={"ordering": ["consumable"], "verbose_name_plural": "Consumable details"},
        ),
    ]
