"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import code_size_analyzer_client
from code_size_analyzer_client.model.map_file_section import MapFileSection


class TestMapFileSection(unittest.TestCase):
    """MapFileSection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMapFileSection(self):
        """Test MapFileSection"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MapFileSection()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
