# coding: utf-8

"""
    FAB backend

    FAB backend API

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import unittest

from fab_clientlib.models.submissions_post200_response_all_of_body import SubmissionsPost200ResponseAllOfBody


class TestSubmissionsPost200ResponseAllOfBody(unittest.TestCase):
  """SubmissionsPost200ResponseAllOfBody unit test stubs"""

  def setUp(self):
    pass

  def tearDown(self):
    pass

  def make_instance(self, include_optional) -> SubmissionsPost200ResponseAllOfBody:
    """Test SubmissionsPost200ResponseAllOfBody
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included """
    # uncomment below to create an instance of `SubmissionsPost200ResponseAllOfBody`
    """
    model = SubmissionsPost200ResponseAllOfBody()
    if include_optional:
        return SubmissionsPost200ResponseAllOfBody(
            id = ''
        )
    else:
        return SubmissionsPost200ResponseAllOfBody(
    )
    """

  def testSubmissionsPost200ResponseAllOfBody(self):
    """Test SubmissionsPost200ResponseAllOfBody"""
    # inst_req_only = self.make_instance(include_optional=False)
    # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
  unittest.main()
