INTERFACE
SUBROUTINE FADDATE (KDATE, PDIFF)

USE PARKIND1, ONLY : JPRB, JPIM

INTEGER (KIND=JPIM), INTENT (INOUT) :: KDATE (22)
REAL (KIND=JPRB),    INTENT (IN)    :: PDIFF

END SUBROUTINE
END INTERFACE

