#ifndef NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION "6.2.2504-8-g2ad9f979"
#define NETGEN_VERSION_MAJOR 6
#define NETGEN_VERSION_MINOR 2
#define NETGEN_VERSION_PATCH 2504
#define NETGEN_VERSION_TWEAK 8
#define NETGEN_VERSION_HASH "g2ad9f979"
#endif // NETGEN_VERSION_HPP_INCLUDED
