# convert { #bindcurve.convert }

```python
convert(
    IC50_df
    model
    RT=None
    LsT=None
    Kds=None
    y0=None
    compound_sel=False
    ci=True
    verbose=False
)
```

Function for converting IC50 to Kd using `coleska`, `cheng_prusoff` and `cheng_prusoff_corr` models.

## Parameters {.doc-section .doc-section-parameters}

| Name         | Type         | Description                                                                                | Default    |
|--------------|--------------|--------------------------------------------------------------------------------------------|------------|
| IC50_df      | DataFrame    | Pandas DataFrame containing the fitted IC50 values.                                        | _required_ |
| model        | str          | Name of the conversion model. Options: `coleska`, `cheng_prusoff`, `cheng_prusoff_corr`    | _required_ |
| RT           | float or int | Total concentration of the receptor.                                                       | `None`     |
| LsT          | float or int | Total concentration of the labeled ligand.                                                 | `None`     |
| Kds          | float or int | Dissociation constant of the labeled ligand.                                               | `None`     |
| y0           | float or int | Parameter used in the corrected Cheng-Prusoff model.                                       | `None`     |
| compound_sel | list         | List of compounds to execute the function on. If set to False, all compounds will be used. | `False`    |
| ci           | bool         | Whether to calculate 95% confidence intervals.                                             | `True`     |
| verbose      | bool         | If set to "True", more detailed output is printed. Intended mainly for troubleshooting.    | `False`    |

## Returns {.doc-section .doc-section-returns}

| Name   | Type      | Description                                         |
|--------|-----------|-----------------------------------------------------|
|        | DataFrame | Pandas DataFrame containing the conversion results. |