# fit_Kd_competition { #bindcurve.fit_Kd_competition }

```python
fit_Kd_competition(
    input_df
    model
    RT
    LsT
    Kds
    N=None
    compound_sel=False
    fix_ymin=False
    fix_ymax=False
    ci=True
    verbose=False
)
```

Function for fitting the `comp_3st_specific`, `comp_3st_total`, `comp_4st_specific` and `comp_4st_total` models.

## Parameters {.doc-section .doc-section-parameters}

| Name         | Type         | Description                                                                                                               | Default    |
|--------------|--------------|---------------------------------------------------------------------------------------------------------------------------|------------|
| input_df     | DataFrame    | Pandas DataFrame containing the input data.                                                                               | _required_ |
| model        | str          | Name of the model. Options: `comp_3st_specific`, `comp_3st_total`, `comp_4st_specific`, `comp_4st_total`                  | _required_ |
| RT           | float or int | Total concentration of the receptor.                                                                                      | _required_ |
| LsT          | float or int | Total concentration of the labeled ligand.                                                                                | _required_ |
| Kds          | float or int | Dissociation constant of the labeled ligand.                                                                              | _required_ |
| N            | float or int | Parameter for nonspecific binding of the unlabeled ligand (needed only for `comp_3st_total` and `comp_4st_total` models). | `None`     |
| compound_sel | list         | List of compounds to execute the function on. If set to False, all compounds will be used.                                | `False`    |
| fix_ymin     | float or int | Lower asymptote of the model will be fixed at the provided value. If set to "False", it will be fitted freely.            | `False`    |
| fix_ymax     | float or int | Upper asymptote of the model will be fixed at the provided value. If set to "False", it will be fitted freely.            | `False`    |
| ci           | bool         | Whether to calculate 95% confidence intervals.                                                                            | `True`     |
| verbose      | bool         | If set to "True", more detailed output is printed. Intended mainly for troubleshooting.                                   | `False`    |

## Returns {.doc-section .doc-section-returns}

| Name   | Type      | Description                                  |
|--------|-----------|----------------------------------------------|
|        | DataFrame | Pandas DataFrame containing the fit results. |