# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/web-bot-auth',
                'doc_host': 'https://Fewsats.github.io',
                'git_url': 'https://github.com/Fewsats/web-bot-auth',
                'lib_path': 'web_bot_auth'},
  'syms': {'web_bot_auth.core': {'web_bot_auth.core.foo': ('core.html#foo', 'web_bot_auth/core.py')}}}
