
:toc: left
:toclevels: 6

++++
  <style>
  .first-sentence {
    text-align: left;
    margin-left: 0%;
    margin-right: auto;
    width: 66%;
    background: Beige;
  }
  .last-sentence {
    text-align: right;
    margin-left: auto;
    margin-right: 0%;
    width: 66%;
    background: AliceBlue;
  }
  </style>
++++
= Wordy machines
[.first-sentence]
Part 1 kicks off your natural language processing (NLP) adventure with an introduction to some real-world applications.

[.last-sentence]
Part 1 kicks off your natural language processing (NLP) adventure with an introduction to some real-world applications.

[.first-sentence]
In chapter 1, you'll quickly begin to think of ways you can use machines that process words in your own life.

[.last-sentence]
Words are the foundation of any language, whether it's the keywords in a programming language or the natural language words you learned as a child.

[.first-sentence]
In chapter 2, we give you the tools you need to teach machines to extract words from documents.

[.last-sentence]
You'll learn how to automatically group natural language words together into groups of words with similar meaning without having to hand-craft synonym lists.

[.first-sentence]
In chapter 3, we count those words and assemble them into vectors that represent the meaning of a document.

[.last-sentence]
You can use these vectors to represent the meaning of an entire document, whether it's a 280-character tweet or a 500-page novel.

[.first-sentence]
In chapter 4, you'll discover some time-tested math tricks to compress your vectors down to much more useful topic vectors.

[.last-sentence]
In chapter 4, you'll discover some time-tested math tricks to compress your vectors down to much more useful topic vectors.

[.first-sentence]
By the end of part 1, you'll have the tools you need for many interesting NLP applications -- from semantic search to chatbots.

[.last-sentence]
By the end of part 1, you'll have the tools you need for many interesting NLP applications -- from semantic search to chatbots.

