
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-07-03T17:25:38+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "ef5d828b8c776569fef82bba9bde41a979a15415",
 "version": "1.1.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
