# flake8: noqa
from keplemon.enums import SAALKeyMode

def get_key_mode() -> SAALKeyMode: ...
def set_key_mode(mode: SAALKeyMode) -> None: ...
def topo_equinox_to_date(yr_of_equinox: int, ds50utc: float, ra: float, dec: float) -> tuple[float, float]: ...
def topo_date_to_epoch(ds50_in: float, ra: float, dec: float, ds50_out: float) -> tuple[float, float]: ...
def topo_epoch_to_date(ds50_in: float, ra: float, dec: float, ds50_out: float) -> tuple[float, float]: ...
