# stephanie/constants.py

# ==== Context Keys ====
AGENT = "Agent"
API_BASE = "api_base"
API_KEY = "api_key"
BATCH_SIZE = "batch_size"
CONTEXT = "context"
DEFAULT = "default"
DETAILS = "details"
EVOLVED = "evolved"
FEEDBACK = "feedback"
FILE = "file"
GOAL = "goal"
GOAL_TYPE = "goal_type"
GOAL_TEXT = "goal_text"
HYPOTHESES = "hypotheses"
DATABASE_MATCHES = "database_matches"
TEXT = "text"
LITERATURE = "literature"
LOOKAHEAD = "lookahead"
MODEL = "model"
NAME = "name"
PIPELINE = "pipeline"
PROXIMITY = "proximity"
RANKING = "ranking"
REFLECTION = "reflection"
REVIEW = "review"
REVIEWS = "reviews"
RUN_ID = "run_id"
PIPELINE_RUN_ID="pipeline_run_id"
SCORE = "score"
SOURCE = "source"
STAGE = "stage"
STRATEGY = "strategy"
VERSION = "version"

# ==== Config Keys ====
DATABASE = "database"
EVENT = "event"
INPUT_KEY = "input_key"
OUTPUT_KEY = "output_key"
PROMPT_DIR = "prompt_dir"
PROMPT_FILE = "prompt_file"
PROMPT_MATCH_RE = "prompt_match_re"
PROMPT_MODE = "prompt_mode"
PROMPT_PATH = "prompt_path"
SAVE_CONTEXT = "save_context"
SAVE_PROMPT = "save_prompt"
SKIP_IF_COMPLETED = "skip_if_completed"
