from .jsacm import login
from .jsacm import greet
from .jsacm import calc
from .jsacm import agecalc
from .jsacm import gettime
from .jsacm import getdate
from .jsacm import getday
from .jsacm import createfile
from .jsacm import writefile
from .jsacm import appendfile
from .jsacm import deletefile
from .jsacm import readfile
from .jsacm import dbsearch
from .jsacm import dbedit
from .jsacm import rps
from .jsacm import createtodolist
from .jsacm import addtask
from .jsacm import checkofftask
from .jsacm import deletetask
from .jsacm import opentodolist
from .jsacm import fileconvert
from .jsacm import translate
from .jsacm import aid
from .jsacm import ewans
from .jsacm import caesarcypher
from .jsacm import profitcalc
from .jsacm import namegen
from .jsacm import convert
from .jsacm import rickroll
from .jsacm import ytplay
from .jsacm import ytdownload
# 'method' is a function that is present in a file called 'file.py'