
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-07-03T16:24:48-0600",
 "dirty": true,
 "error": null,
 "full-revisionid": "4304c30c58dbc822ed71906b047f87783a1d13f1",
 "version": "2.65.0rc3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
