from typing import List
from numpy import ndarray

def sum_nparr_int32(np_array: List[int] | ndarray) -> int: ...
def sum_arr_int32(array: List[int]) -> int: ...
def sum_two_nparr_floats32(
    arr_1: List[float] | ndarray, arr_2: List[float] | ndarray, method: str
) -> List: ...
def sum_two_floats32(arr_1: List[float], arr_2: List[float], method: str) -> List: ...
def sum_two_nparr_ints32(
    arr_1: List[int] | ndarray, arr_2: List[int] | ndarray, method: str
) -> List: ...
def sum_two_ints32(arr_1: List[int], arr_2: List[int]) -> List: ...
def multiply_two_nparr_ints32(
    arr_1: List[int] | ndarray, arr_2: List[int] | ndarray
) -> List: ...
def multiply_two_ints32(arr_1: List[int], arr_2: List[int], method: str) -> List: ...
