
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-07-02T10:30:35-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "cd9aa2f5e7ed5c57bff3cff6af259ceae63728b3",
 "version": "2.64.5rc3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
