# coding: utf-8

"""
    Live Data People API

    This API provides information about people as observed by Live Data

    The version of the OpenAPI document: 1.0
    Contact: support@livedatatechnologies.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from ldt_people_client_async_staging.models.find_preview200_response_matches_inner_people_inner import FindPreview200ResponseMatchesInnerPeopleInner
from typing import Optional, Set
from typing_extensions import Self

class FindPreview200ResponseMatchesInner(BaseModel):
    """
    FindPreview200ResponseMatchesInner
    """ # noqa: E501
    people: Optional[List[FindPreview200ResponseMatchesInnerPeopleInner]] = Field(default=None, description="The people that matched the provided filters. Maximum of 5 returned in this endpoint (use `/search` for larger queries).")
    found: Optional[StrictBool] = Field(default=None, description="Indicates whether there was at least one hit given the provided inputs.")
    __properties: ClassVar[List[str]] = ["people", "found"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FindPreview200ResponseMatchesInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in people (list)
        _items = []
        if self.people:
            for _item_people in self.people:
                if _item_people:
                    _items.append(_item_people.to_dict())
            _dict['people'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FindPreview200ResponseMatchesInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "people": [FindPreview200ResponseMatchesInnerPeopleInner.from_dict(_item) for _item in obj["people"]] if obj.get("people") is not None else None,
            "found": obj.get("found")
        })
        return _obj


