# coding: utf-8
# file generated by setuptools_scm + setup.py
# don't change, don't track in version control
git_hash = b'\xcd\x92(\x8e'
full_git_hash = 'cd92288e833cfc4e651f81e18fd1a4bbea9ce528'
git_branch = 'HEAD'
dirty = False
