from .jsacm import login
from .jsacm import greet
from .jsacm import calc
from .jsacm import agecalc
from .jsacm import gettime
from .jsacm import getdate
from .jsacm import getday
from .jsacm import createfile
from .jsacm import writefile
from .jsacm import appendfile
from .jsacm import deletefile
from .jsacm import readfile
from .jsacm import dbsearch
from .jsacm import dbedit
from .jsacm import rps
from .jsacm import createtodolist
from .jsacm import addtask
from .jsacm import checkofftask
from .jsacm import deletetask
from .jsacm import opentodolist
from .jsacm import fileconvert
from .jsacm import translate
from .jsacm import aid
from .jsacm import ewans
from .jsacm import profitcalc
from .jsacm import namegen
from .jsacm import convert
from .jsacm import rickroll
from .jsacm import ytplay
from .jsacm import ytdownload
from .jsacm import ceasar_encryption
from .jsacm import ceasar_decryption
from .jsacm import keyboard_encryption
from .jsacm import keyboard_decryption
from .jsacm import atbash_encryption
from .jsacm import atbash_decryption
from .jsacm import asymetrical_encryption
from .jsacm import asymetrical_decryption
from .jsacm import bogosort
from .jsacm import stalinsort
from .jsacm import bubblesort
from .jsacm import linearsearch
from .jsacm import denary2binary
from .jsacm import binary2denary
from .jsacm import denary2hexadecimal
from .jsacm import denary2numeral
from .jsacm import numeral2denary
from .jsacm import english2morse
from .jsacm import morse2english
from .jsacm import passgen
# 'method' is a function that is present in a file called 'file.py'