# coding: utf-8

"""
Earnix import export API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.0.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401

from pydantic.v1 import Field, constr

from earnix_elevate.clients.imx.models.create_connection_request import (
    CreateConnectionRequest,
)


class CreateDatabricksDeltashareConnectionRequest(CreateConnectionRequest):
    """
    CreateDatabricksDeltashareConnectionRequest
    """

    deltashare_profile: constr(strict=True, max_length=8192, min_length=20) = Field(
        default=..., alias="deltashareProfile"
    )
    __properties = ["name", "description", "tags", "type", "deltashareProfile"]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> CreateDatabricksDeltashareConnectionRequest:
        """Create an instance of CreateDatabricksDeltashareConnectionRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        # set to None if description (nullable) is None
        # and __fields_set__ contains the field
        if self.description is None and "description" in self.__fields_set__:
            _dict["description"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> CreateDatabricksDeltashareConnectionRequest:
        """Create an instance of CreateDatabricksDeltashareConnectionRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return CreateDatabricksDeltashareConnectionRequest.parse_obj(obj)

        _obj = CreateDatabricksDeltashareConnectionRequest.parse_obj(
            {
                "name": obj.get("name"),
                "description": obj.get("description"),
                "tags": obj.get("tags"),
                "type": obj.get("type"),
                "deltashare_profile": obj.get("deltashareProfile"),
            }
        )
        return _obj
