
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-07-02T21:17:39+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "815671d5f53ab7bf0cabe9ba685b70285da38a27",
 "version": "2.31.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
