# Generated by Django 4.2.16 on 2024-11-28 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "magic_notifier",
            "0002_notification_expires_notification_is_encrypted_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="inited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="magic_notifications_inited",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
