# flake8: noqa

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.1.0"

# import ApiClient
from code_size_analyzer_client.api_client import ApiClient

# import Configuration
from code_size_analyzer_client.configuration import Configuration

# import exceptions
from code_size_analyzer_client.exceptions import OpenApiException
from code_size_analyzer_client.exceptions import ApiAttributeError
from code_size_analyzer_client.exceptions import ApiTypeError
from code_size_analyzer_client.exceptions import ApiValueError
from code_size_analyzer_client.exceptions import ApiKeyError
from code_size_analyzer_client.exceptions import ApiException
