"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from censys_platform.types import BaseModel
from typing_extensions import TypedDict


class CrudUpdateInputBodyTypedDict(TypedDict):
    description: str
    r"""description of the collection"""
    name: str
    r"""name of the collection"""
    query: str
    r"""query string to search upon to build the collection"""


class CrudUpdateInputBody(BaseModel):
    description: str
    r"""description of the collection"""

    name: str
    r"""name of the collection"""

    query: str
    r"""query string to search upon to build the collection"""
