CREATE OR REPLACE FUNCTION MAP_LICENSE_SOURCE_EN AS (x) ->
    CASE 
        WHEN x = -1001    THEN 'Mohammed Bin Rashid Foundation to Support Youth Projects'
        WHEN x = -60      THEN 'Dubai Expo City Authority'
        WHEN x = -40      THEN 'Real Estate Regulatory Authority'
        WHEN x = -10      THEN 'Dubai Economic Department'
        WHEN x = 1        THEN 'Department of Islamic Affairs and Charitable Activities'
        WHEN x = 70       THEN 'Dubai Government'
        WHEN x = 275      THEN 'Dubai Multi Commodities Center Authority'
        WHEN x = 1001     THEN 'RUFI Downtown Residency Limited'
        WHEN x = 4341     THEN 'TECOM Investments Free Zone (LLC)'
        WHEN x = 4386     THEN 'Mohammed Bin Rashid Foundation for SME Development'
        WHEN x = 4406     THEN 'Dubai Healthcare City Free Zone (LLC)'
        WHEN x = 4448     THEN 'Dubai Silicon Oasis Authority'
        WHEN x = 4421     THEN 'Ports, Customs and Free Zone Corporation'
        WHEN x = 4501     THEN 'Dubai Multi Commodities Centre'
        WHEN x = 4506     THEN 'TECOM Investments Free Zone (LLC)'
        WHEN x = 5073     THEN 'Jebel Ali Free Zone Authority'
        WHEN x = 5235     THEN 'Real Estate Department'
        WHEN x = 5527     THEN 'Dubai Aviation City Corporation'
        WHEN x = 6566     THEN 'Dubai Silicon Oasis Authority'
        WHEN x = 6666     THEN 'Meydan City Corporation'
        WHEN x = 615504   THEN 'Dubai Integrated Economic Zones Authority'
        WHEN x = 616289   THEN 'FRH Real Estate Investment Limited'
        WHEN x = 4249418  THEN 'Trakheesi'
        WHEN x = 6495571  THEN 'Other'
        WHEN x = 10686091 THEN 'Dubai World Central'
        WHEN x = 23398803 THEN 'Others'
        WHEN x = 23398876 THEN 'Off Shore'
        WHEN x = 73965376 THEN 'Trakheesi'
    END;

CREATE OR REPLACE FUNCTION MAP_LICENSE_SOURCE_AR AS (x) ->
    CASE 
        WHEN x = -1001    THEN 'مؤسسة محمد بن راشد لدعم مشاريع الشباب'
        WHEN x = -60      THEN 'سلطة مدينة اكسبو دبي'
        WHEN x = -40      THEN 'مؤسسة التنظيم العقاري'
        WHEN x = -10      THEN 'دائرة التنمية الاقتصادية'
        WHEN x = 1        THEN 'دائره الشؤون الاسلاميه والعمل الخيرى'
        WHEN x = 70       THEN 'حكومه دبى'
        WHEN x = 275      THEN 'مركز دبي للسلع المتعددة'
        WHEN x = 1001     THEN 'روفى داون تاون رسيدينسى ليمتد'
        WHEN x = 4341     THEN 'تيكوم للإستثمارات منطقة حرة- ذ.م.م'
        WHEN x = 4386     THEN 'مؤسسه محمد بن راشد لدعم مشاريع الشباب'
        WHEN x = 4406     THEN 'مدينه دبى الطبيه منطقه حرة - ذ.م.م.'
        WHEN x = 4448     THEN 'سلطه واحة دبي للسيليكون'
        WHEN x = 4421     THEN 'مؤسسه الموانئ والجمارك والمنطقه الحره'
        WHEN x = 4501     THEN 'مركز دبى للسلع المتعدده'
        WHEN x = 4506     THEN 'تيكوم للإستثمارات منطقه حره  ذ.م.م'
        WHEN x = 5073     THEN 'سلطه المنطقه الحره لجبل على'
        WHEN x = 5235     THEN 'دائره العقارات'
        WHEN x = 5527     THEN 'مؤسسه مدينه دبى للطيران'
        WHEN x = 6566     THEN 'سلطه واحه دبى للسيليكون'
        WHEN x = 6666     THEN 'مؤسسة مدينة ميدان'
        WHEN x = 615504   THEN 'سلطة دبي للمناطق الإقتصادية المتكاملة'
        WHEN x = 616289   THEN 'اف.آر.آتش ريال ايستيت انفيستمينت ليمتد'
        WHEN x = 4249418  THEN 'تراخيص'
        WHEN x = 6495571  THEN 'أخرى'
        WHEN x = 10686091 THEN 'دبي ورلد سنترال'
        WHEN x = 23398803 THEN 'أخرى'
        WHEN x = 23398876 THEN 'اوف شور'
        WHEN x = 73965376 THEN 'تراخيص-الدائرة الاقتصادية'
    END;