CREATE OR REPLACE FUNCTION MAP_NATIONALITY_EN AS (x) ->
    CASE 
        WHEN x = 1   THEN 'United Arab Emirates'
        WHEN x = 2   THEN 'Kuwait'
        WHEN x = 3   THEN 'Bahrain'
        WHEN x = 6   THEN 'Saudi Arabia'
        WHEN x = 7   THEN 'Lebanon'
        WHEN x = 8   THEN 'Syria'
        WHEN x = 9   THEN 'Jordan'
        WHEN x = 11  THEN 'Iraq'
        WHEN x = 13  THEN 'Egypt'
        WHEN x = 21  THEN 'India'
        WHEN x = 22  THEN 'Pakistan'
        WHEN x = 26  THEN 'United Kingdom'
        WHEN x = 28  THEN 'Australia'
        WHEN x = 31  THEN 'Canada'
        WHEN x = 39  THEN 'Germany'
        WHEN x = 43  THEN 'Zimbabwe'
        WHEN x = 45  THEN 'Ireland'
        WHEN x = 48  THEN 'Kazakhstan'
        WHEN x = 52  THEN 'Poland'
        WHEN x = 59  THEN 'Sri Lanka'
        WHEN x = 60  THEN 'Azerbaijan'
        WHEN x = 61  THEN 'Hungary'
        WHEN x = 64  THEN 'Philippines'
        WHEN x = 78  THEN 'Indonesia'
        WHEN x = 82  THEN 'Ukraine'
        WHEN x = 93  THEN 'New Zealand'
        WHEN x = 98  THEN 'Portugal'
        WHEN x = 103 THEN 'Uganda'
        WHEN x = 108 THEN 'Serbia'
        WHEN x = 109 THEN 'Zambia'
        WHEN x = 136 THEN 'Dominica'
        WHEN x = 209 THEN 'Netherlands'
    END;

CREATE OR REPLACE FUNCTION MAP_NATIONALITY_AR AS (x) ->
    CASE 
        WHEN x = 1   THEN 'الإمارات العربية المتحدة'
        WHEN x = 2   THEN 'الكويت'
        WHEN x = 3   THEN 'مملكة البحرين'
        WHEN x = 6   THEN 'المملكة العربية السعودية'
        WHEN x = 7   THEN 'لبنان'
        WHEN x = 8   THEN 'سوريا'
        WHEN x = 9   THEN 'الاردن'
        WHEN x = 11  THEN 'العراق'
        WHEN x = 13  THEN 'مصر'
        WHEN x = 21  THEN 'الهند'
        WHEN x = 22  THEN 'باكستان'
        WHEN x = 26  THEN 'المملكة المتحدة'
        WHEN x = 28  THEN 'استراليا'
        WHEN x = 31  THEN 'كندا'
        WHEN x = 39  THEN 'المانيا'
        WHEN x = 43  THEN 'زيمبابواي'
        WHEN x = 45  THEN 'ايرلندا'
        WHEN x = 48  THEN 'كازاخستان'
        WHEN x = 52  THEN 'بولندا'
        WHEN x = 59  THEN 'سيريلانكا'
        WHEN x = 60  THEN 'أذربيجان'
        WHEN x = 61  THEN 'المجر'
        WHEN x = 64  THEN 'الفلبين'
        WHEN x = 78  THEN 'اندونسيا'
        WHEN x = 82  THEN 'أوكرانيا'
        WHEN x = 93  THEN 'نيوزلندا'
        WHEN x = 98  THEN 'البرتغال'
        WHEN x = 103 THEN 'أوغندا'
        WHEN x = 108 THEN 'صربيا'
        WHEN x = 109 THEN 'زامبيا'
        WHEN x = 136 THEN 'دومينيكا'
        WHEN x = 209 THEN 'هولندا'
    END;