# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim

# Install dependencies
RUN pip install --no-cache-dir fastmcp bibextract

# Set working directory
WORKDIR /app

# Copy the MCP server script
COPY bibextract_mcp.py /app/bibextract_mcp.py

# Default command
ENTRYPOINT ["python", "bibextract_mcp.py"]
