"""Text strings for psiutils."""

DELETE_THESE_ITEMS = 'Are you sure you want to delete these item(s)?'
NO_SUCH_FILE = 'no such file or directory'

OK = 'OK'
HELP = 'Help'
EXIT = 'Exit'
QUIT = 'Quit'
CANCEL = 'Cancel'
CLOSE = 'Close'
COPY = 'Copy'
COMPARE = 'Compare'
DIFF = 'Diff'
EDIT = 'Edit'
BUILD = 'Build'
EVENT = 'Event'
SAVE = 'Save'
SAVE_PDF = 'Save as PDF'
NEW = 'New'
YES = 'Yes'
NO = 'No'
REFRESH = 'Refresh'
DELETE = 'Delete'
OPEN = 'Open'
SEND = 'Send'
PREVIOUS = 'Prev'
NEXT = 'Next'
