"""Typing hints for FPy programs"""

from fpy2.ops import Real

PI: Real = ...
E: Real = ...
NAN: Real = ...
INFINITY: Real = ...
LOG2E: Real = ...
LOG10E: Real = ...
LN2: Real = ...
PI_2: Real = ...
PI_4: Real = ...
M_1_PI: Real = ...
M_2_PI: Real = ...
M_2_SQRTPI: Real = ...
SQRT2: Real = ...
SQRT1_2: Real = ...
