# coding: utf-8

"""
    Smstools API

    The integration of our SMS gateway is simple. Integrate our SMS API and easily provide your website or software package with text messaging features in minutes.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import smstools
from smstools.models.create_message_template_request import CreateMessageTemplateRequest  # noqa: E501
from smstools.rest import ApiException

class TestCreateMessageTemplateRequest(unittest.TestCase):
    """CreateMessageTemplateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test CreateMessageTemplateRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateMessageTemplateRequest`
        """
        model = smstools.models.create_message_template_request.CreateMessageTemplateRequest()  # noqa: E501
        if include_optional :
            return CreateMessageTemplateRequest(
                title = '', 
                message = '', 
                order = 56
            )
        else :
            return CreateMessageTemplateRequest(
                message = '',
                order = 56,
        )
        """

    def testCreateMessageTemplateRequest(self):
        """Test CreateMessageTemplateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
