# coding: utf-8

"""
    Smstools API

    The integration of our SMS gateway is simple. Integrate our SMS API and easily provide your website or software package with text messaging features in minutes.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v1_message_send_post_request import V1MessageSendPostRequest

class TestV1MessageSendPostRequest(unittest.TestCase):
    """V1MessageSendPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1MessageSendPostRequest:
        """Test V1MessageSendPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1MessageSendPostRequest`
        """
        model = V1MessageSendPostRequest()
        if include_optional:
            return V1MessageSendPostRequest(
                message = '',
                to = '',
                sender = ''
            )
        else:
            return V1MessageSendPostRequest(
        )
        """

    def testV1MessageSendPostRequest(self):
        """Test V1MessageSendPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
