"""
å…¨é¢æµ‹è¯•SimpleCAD APIçš„é«˜çº§åŠŸèƒ½å’Œå»ºæ¨¡æ“ä½œ
åŒ…æ‹¬å¤æ‚é›¶ä»¶æ„å»ºï¼Œå¦‚æ³•å…°ã€é½¿è½®ç­‰
"""

import sys
import os
import math
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'src'))

from simplecadapi import *
from simplecadapi.operations import helical_sweep, helical_sweep

def export_model(body, filename, description="æ¨¡å‹"):
    """é€šç”¨çš„æ¨¡å‹å¯¼å‡ºå‡½æ•°"""
    if body is None or not body.is_valid():
        print(f"   âœ— {description}å¯¼å‡ºå¤±è´¥: æ— æ•ˆçš„Bodyå¯¹è±¡")
        return False
    
    try:
        import cadquery as cq
        output_dir = "output"
        os.makedirs(output_dir, exist_ok=True)
        
        wp = cq.Workplane().add(body.cq_solid)
        
        # å¯¼å‡ºSTL
        stl_path = f"{output_dir}/{filename}.stl"
        cq.exporters.export(wp, stl_path)
        
        print(f"   âœ“ {description}å·²å¯¼å‡ºä¸º {filename}.stl")
        
        return True
        
    except Exception as e:
        print(f"   âœ— {description}å¯¼å‡ºå¤±è´¥: {e}")
        return False

def test_extrude_operations():
    """æµ‹è¯•æ‹‰ä¼¸æ“ä½œ"""
    print("=== æµ‹è¯•æ‹‰ä¼¸æ“ä½œ ===")
    
    results = []
    
    try:
        # æµ‹è¯•ç®€å•çŸ©å½¢æ‹‰ä¼¸
        rect = make_rectangle(2.0, 1.0, center=True)
        extruded_rect = extrude(rect, distance=0.5)
        print(f"âœ“ çŸ©å½¢æ‹‰ä¼¸æˆåŠŸ: {extruded_rect}")
        results.append(extruded_rect)
        export_model(extruded_rect, "01_extruded_rectangle", "æ‹‰ä¼¸çŸ©å½¢")
        
        # æµ‹è¯•åœ†å½¢æ‹‰ä¼¸
        circle = make_circle(0.5)
        extruded_circle = extrude(circle, distance=1.0)
        print(f"âœ“ åœ†å½¢æ‹‰ä¼¸æˆåŠŸ: {extruded_circle}")
        results.append(extruded_circle)
        export_model(extruded_circle, "02_extruded_circle", "æ‹‰ä¼¸åœ†å½¢")
        
        # åˆ›å»ºç»„åˆæ¨¡å‹å±•ç¤ºæ‰€æœ‰æ‹‰ä¼¸ç»“æœ
        if len(results) >= 2:
            combined = results[0]
            # åœ¨ä¸åŒä½ç½®æ”¾ç½®å…¶ä»–æ‹‰ä¼¸ä½“
            with LocalCoordinateSystem(origin=(3, 0, 0), x_axis=(1, 0, 0), y_axis=(0, 1, 0)):
                combined = union(combined, results[1])
            if len(results) >= 3:
                with LocalCoordinateSystem(origin=(0, 3, 0), x_axis=(1, 0, 0), y_axis=(0, 1, 0)):
                    combined = union(combined, results[2])
            export_model(combined, "04_extrude_operations_combined", "æ‹‰ä¼¸æ“ä½œç»„åˆ")
        
        return True
        
    except Exception as e:
        print(f"âœ— æ‹‰ä¼¸æ“ä½œæµ‹è¯•å¤±è´¥: {e}")
        return False


def test_revolve_operations():
    """æµ‹è¯•æ—‹è½¬æ“ä½œ"""
    print("\n=== æµ‹è¯•æ—‹è½¬æ“ä½œ ===")
    
    results = []
    
    try:
        # åˆ›å»ºLå‹è½®å»“è¿›è¡Œæ—‹è½¬
        p1 = make_point(0.5, 0, 0)
        p2 = make_point(1.0, 0, 0)
        p3 = make_point(1.0, 0, 0.5)
        p4 = make_point(0.8, 0, 0.5)
        p5 = make_point(0.8, 0, 0.2)
        p6 = make_point(0.5, 0, 0.2)
        
        lines = [
            make_line([p1, p2], "segment"),
            make_line([p2, p3], "segment"),
            make_line([p3, p4], "segment"),
            make_line([p4, p5], "segment"),
            make_line([p5, p6], "segment"),
            make_line([p6, p1], "segment")
        ]
        
        l_profile = make_sketch(lines)
        
        # ç»•Zè½´æ—‹è½¬åˆ›å»ºå›è½¬ä½“
        axis_start = make_point(0, 0, -1)
        axis_end = make_point(0, 0, 1)
        revolved = revolve(l_profile, axis_start, axis_end, 2 * math.pi)
        
        print(f"âœ“ Lå‹è½®å»“æ—‹è½¬æˆåŠŸ: {revolved}")
        results.append(revolved)
        export_model(revolved, "05_revolved_l_profile", "Lå‹è½®å»“æ—‹è½¬ä½“")
        
        # æµ‹è¯•éƒ¨åˆ†æ—‹è½¬ï¼ˆ180åº¦ï¼‰
        half_revolved = revolve(l_profile, axis_start, axis_end, math.pi)
        print(f"âœ“ 180åº¦æ—‹è½¬æˆåŠŸ: {half_revolved}")
        results.append(half_revolved)
        export_model(half_revolved, "06_half_revolved", "180åº¦æ—‹è½¬ä½“")
        
        # åˆ›å»ºç»„åˆå±•ç¤º
        if len(results) >= 2:
            with LocalCoordinateSystem(origin=(3, 0, 0), x_axis=(1, 0, 0), y_axis=(0, 1, 0)):
                combined = union(results[0], results[1])
                export_model(combined, "07_revolve_operations_combined", "æ—‹è½¬æ“ä½œç»„åˆ")
        
        return True
        
    except Exception as e:
        print(f"âœ— æ—‹è½¬æ“ä½œæµ‹è¯•å¤±è´¥: {e}")
        return False


def test_loft_operations():
    """æµ‹è¯•æ”¾æ ·æ“ä½œ"""
    print("\n=== æµ‹è¯•æ”¾æ ·æ“ä½œ ===")
    
    results = []
    
    try:
        # åˆ›å»ºä¸åŒå¤§å°çš„çŸ©å½¢åœ¨ä¸åŒé«˜åº¦è¿›è¡Œæ”¾æ ·
        print("åˆ›å»ºåˆ†å±‚çŸ©å½¢æ”¾æ ·...")
        
        # åº•å±‚ - å¤§çŸ©å½¢ (z=0)
        rect1 = make_rectangle(2.0, 2.0, center=True)
        
        # ä¸­å±‚ - ä¸­çŸ©å½¢ (z=1)
        with LocalCoordinateSystem(origin=(0, 0, 1), x_axis=(1, 0, 0), y_axis=(0, 1, 0)):
            rect2 = make_rectangle(1.0, 1.0, center=True)
        
        # é¡¶å±‚ - å°çŸ©å½¢ (z=2)
        with LocalCoordinateSystem(origin=(0, 0, 2), x_axis=(1, 0, 0), y_axis=(0, 1, 0)):
            rect3 = make_rectangle(0.5, 0.5, center=True)
        
        lofted = loft([rect1, rect2, rect3])
        print(f"âœ“ å¤šæˆªé¢æ”¾æ ·æˆåŠŸ: {lofted}")
        results.append(lofted)
        export_model(lofted, "08_lofted_rectangles", "åˆ†å±‚çŸ©å½¢æ”¾æ ·")
        
        # æµ‹è¯•åœ†å½¢åˆ°çŸ©å½¢çš„æ”¾æ ·ï¼ˆåœ¨ä¸åŒé«˜åº¦ï¼‰
        print("åˆ›å»ºåœ†å½¢åˆ°çŸ©å½¢æ”¾æ ·...")
        
        # åº•å±‚åœ†å½¢ (z=0)
        circle = make_circle(1.0)
        
        # é¡¶å±‚çŸ©å½¢ (z=1.5)
        with LocalCoordinateSystem(origin=(0, 0, 1.5), x_axis=(1, 0, 0), y_axis=(0, 1, 0)):
            square = make_rectangle(1.5, 1.5, center=True)
        
        circle_to_square = loft([circle, square])
        print(f"âœ“ åœ†å½¢åˆ°çŸ©å½¢æ”¾æ ·æˆåŠŸ: {circle_to_square}")
        results.append(circle_to_square)
        export_model(circle_to_square, "09_circle_to_square_loft", "åœ†å½¢åˆ°çŸ©å½¢æ”¾æ ·")
        
        # åˆ›å»ºæ›´å¤æ‚çš„æ”¾æ · - åœ†å½¢æ¸å˜åˆ°å…­è¾¹å½¢
        print("åˆ›å»ºåœ†å½¢åˆ°å…­è¾¹å½¢æ”¾æ ·...")
        try:
            # åº•å±‚åœ†å½¢
            base_circle = make_circle(0.8)
            
            # ä¸­å±‚ - æ¤­åœ†å½¢ï¼ˆç”¨çŸ©å½¢è¿‘ä¼¼ï¼‰
            with LocalCoordinateSystem(origin=(0, 0, 0.8), x_axis=(1, 0, 0), y_axis=(0, 1, 0)):
                middle_rect = make_rectangle(1.2, 0.8, center=True)
            
            # é¡¶å±‚ - å°çŸ©å½¢
            with LocalCoordinateSystem(origin=(0, 0, 1.6), x_axis=(1, 0, 0), y_axis=(0, 1, 0)):
                top_rect = make_rectangle(0.6, 0.6, center=True)
            
            complex_loft = loft([base_circle, middle_rect, top_rect])
            print(f"âœ“ å¤æ‚æ”¾æ ·æˆåŠŸ: {complex_loft}")
            results.append(complex_loft)
            export_model(complex_loft, "10_complex_loft", "å¤æ‚å½¢çŠ¶æ”¾æ ·")
            
        except Exception as e:
            print(f"   âš ï¸ å¤æ‚æ”¾æ ·è·³è¿‡: {e}")
        
        # åˆ›å»ºç»„åˆå±•ç¤º
        if len(results) >= 2:
            try:
                combined = results[0]
                with LocalCoordinateSystem(origin=(5, 0, 0), x_axis=(1, 0, 0), y_axis=(0, 1, 0)):
                    combined = union(combined, results[1])
                if len(results) >= 3:
                    with LocalCoordinateSystem(origin=(0, 5, 0), x_axis=(1, 0, 0), y_axis=(0, 1, 0)):
                        combined = union(combined, results[2])
                export_model(combined, "11_loft_operations_combined", "æ”¾æ ·æ“ä½œç»„åˆ")
            except Exception as e:
                print(f"   âš ï¸ æ”¾æ ·ç»„åˆå¯¼å‡ºè·³è¿‡: {e}")
        
        return True
        
    except Exception as e:
        print(f"âœ— æ”¾æ ·æ“ä½œæµ‹è¯•å¤±è´¥: {e}")
        return False


def test_sweep_operations():
    """æµ‹è¯•æ‰«æ æ“ä½œ"""
    print("\n=== æµ‹è¯•æ‰«æ æ“ä½œ ===")
    
    results = []
    
    try:
        # æµ‹è¯•1: ç®€å•çš„ç›´çº¿æ‰«æ  - ç¡®ä¿æˆªé¢ä¸è·¯å¾„æ­£ç¡®å¯¹é½
        print("åˆ›å»ºç®€å•ç›´çº¿æ‰«æ ...")
        
        # åœ¨YZå¹³é¢åˆ›å»ºåœ†å½¢æˆªé¢ï¼ˆXæ–¹å‘ä¸ºæ³•å‘é‡ï¼‰
        with LocalCoordinateSystem(origin=(0, 0, 0), 
                                 x_axis=(0, 1, 0),  # Yè½´ä½œä¸ºæ–°çš„Xè½´
                                 y_axis=(0, 0, 1)):  # Zè½´ä½œä¸ºæ–°çš„Yè½´
            profile_circle = make_circle(0.2)
        
        # åˆ›å»ºXæ–¹å‘çš„æ‰«æ è·¯å¾„
        path_start = make_point(0, 0, 0)
        path_end = make_point(2, 1, 1)
        straight_path = make_line([path_start, path_end], "segment")
        
        swept_straight = sweep(profile_circle, straight_path)
        print(f"âœ“ ç›´çº¿æ‰«æ æˆåŠŸ: {swept_straight}")
        results.append(swept_straight)
        export_model(swept_straight, "12_straight_sweep", "ç›´çº¿æ‰«æ ")
        
        # æµ‹è¯•2: å‚ç›´æ‰«æ 
        print("åˆ›å»ºå‚ç›´æ‰«æ ...")
        
        # åœ¨XYå¹³é¢åˆ›å»ºæ–¹å½¢æˆªé¢
        square_profile = make_rectangle(0.3, 0.3, center=True)
        
        # åˆ›å»ºZæ–¹å‘çš„å‚ç›´è·¯å¾„
        vertical_start = make_point(0, 0, 0)
        vertical_end = make_point(0, 0, 2)
        vertical_path = make_line([vertical_start, vertical_end], "segment")
        
        swept_vertical = sweep(square_profile, vertical_path)
        print(f"âœ“ å‚ç›´æ‰«æ æˆåŠŸ: {swept_vertical}")
        results.append(swept_vertical)
        export_model(swept_vertical, "13_vertical_sweep", "å‚ç›´æ‰«æ ")
        
        # æµ‹è¯•3: æ°´å¹³æ‰«æ 
        print("åˆ›å»ºæ°´å¹³æ‰«æ ...")
        
        # åœ¨XZå¹³é¢åˆ›å»ºä¸‰è§’å½¢è¿‘ä¼¼æˆªé¢ï¼ˆç”¨å°çŸ©å½¢ï¼‰
        with LocalCoordinateSystem(origin=(0, 0, 0), 
                                 x_axis=(1, 0, 0),  # Xè½´ä¿æŒ
                                 y_axis=(0, 0, 1)):  # Zè½´ä½œä¸ºæ–°çš„Yè½´
            triangle_profile = make_rectangle(0.15, 0.25, center=True)
        
        # åˆ›å»ºYæ–¹å‘çš„æ°´å¹³è·¯å¾„
        horizontal_start = make_point(0, 0, 0)
        horizontal_end = make_point(0, 3, 0)
        horizontal_path = make_line([horizontal_start, horizontal_end], "segment")
        
        swept_horizontal = sweep(triangle_profile, horizontal_path)
        print(f"âœ“ æ°´å¹³æ‰«æ æˆåŠŸ: {swept_horizontal}")
        results.append(swept_horizontal)
        export_model(swept_horizontal, "14_horizontal_sweep", "æ°´å¹³æ‰«æ ")
        
        # æµ‹è¯•4: æ–œå‘æ‰«æ 
        print("åˆ›å»ºæ–œå‘æ‰«æ ...")
        
        # è®¡ç®—æ–œå‘è·¯å¾„çš„æ–¹å‘
        diagonal_start = make_point(0, 0, 0)
        diagonal_end = make_point(1, 1, 1)
        
        # è®¡ç®—è·¯å¾„æ–¹å‘å‘é‡
        direction = (1, 1, 1)
        # æ ‡å‡†åŒ–
        length = math.sqrt(sum(d*d for d in direction))
        norm_dir = tuple(d/length for d in direction)
        
        # åˆ›å»ºå‚ç›´äºè·¯å¾„çš„æˆªé¢
        # ä½¿ç”¨ä¸€ä¸ªç®€å•çš„å‚ç›´å‘é‡
        if abs(norm_dir[2]) < 0.9:  # å¦‚æœä¸æ˜¯ä¸»è¦åœ¨Zæ–¹å‘
            perp1 = (0, 0, 1)  # ä½¿ç”¨Zè½´
        else:
            perp1 = (1, 0, 0)  # ä½¿ç”¨Xè½´
        
        # è®¡ç®—ç¬¬äºŒä¸ªå‚ç›´å‘é‡
        # perp2 = cross(norm_dir, perp1)
        perp2 = (
            norm_dir[1] * perp1[2] - norm_dir[2] * perp1[1],
            norm_dir[2] * perp1[0] - norm_dir[0] * perp1[2],
            norm_dir[0] * perp1[1] - norm_dir[1] * perp1[0]
        )
        
        with LocalCoordinateSystem(origin=(0, 0, 0), 
                                 x_axis=perp1, 
                                 y_axis=perp2):
            diagonal_profile = make_circle(0.15)
        
        diagonal_path = make_line([diagonal_start, diagonal_end], "segment")
        
        swept_diagonal = sweep(diagonal_profile, diagonal_path)
        print(f"âœ“ æ–œå‘æ‰«æ æˆåŠŸ: {swept_diagonal}")
        results.append(swept_diagonal)
        export_model(swept_diagonal, "15_diagonal_sweep", "æ–œå‘æ‰«æ ")
        
        # åˆ›å»ºç»„åˆå±•ç¤º
        if len(results) >= 2:
            try:
                combined = results[0]
                positions = [(3, 0, 0), (0, 4, 0), (3, 4, 0)]
                for i, pos in enumerate(positions):
                    if i + 1 < len(results):
                        with LocalCoordinateSystem(origin=pos, x_axis=(1, 0, 0), y_axis=(0, 1, 0)):
                            combined = union(combined, results[i + 1])
                
                export_model(combined, "16_sweep_operations_combined", "æ‰«æ æ“ä½œç»„åˆ")
            except Exception as e:
                print(f"   âš ï¸ æ‰«æ ç»„åˆå¯¼å‡ºè·³è¿‡: {e}")
        
        return True
        
    except Exception as e:
        print(f"âœ— æ‰«æ æ“ä½œæµ‹è¯•å¤±è´¥: {e}")
        return False


def test_advanced_operations():
    """æµ‹è¯•é«˜çº§æ“ä½œ"""
    print("\n=== æµ‹è¯•é«˜çº§æ“ä½œ ===")
    
    results = []
    
    try:
        # åˆ›å»ºåŸºç¡€å®ä½“
        base_box = make_box(1.0, 1.0, 0.2, center=True)
        
        # æµ‹è¯•çº¿æ€§é˜µåˆ—
        linear_array = make_linear_pattern(base_box, direction=(2, 0, 0), count=3, spacing=1.5)
        print(f"âœ“ çº¿æ€§é˜µåˆ—æˆåŠŸ: {linear_array}")
        results.append(linear_array)
        export_model(linear_array, "17_linear_array", "çº¿æ€§é˜µåˆ—")
        
        # æµ‹è¯•2Dé˜µåˆ—ï¼ˆé€šè¿‡ä¸¤æ¬¡çº¿æ€§é˜µåˆ—ï¼‰
        y_array = make_2d_pattern(
            base_box, 
            x_direction=(2, 0, 0), 
            y_direction=(0, 2, 0), 
            x_count=3, 
            y_count=2, 
            x_spacing=1.5, 
            y_spacing=1.5
        )
        print(f"âœ“ 2Dé˜µåˆ—æˆåŠŸ: {y_array}")
        results.append(y_array)
        export_model(y_array, "18_2d_array", "2Dé˜µåˆ—")
        
        # æµ‹è¯•åœ†è§’æ“ä½œ
        test_cube = make_box(2.0, 2.0, 2.0, center=True)
        filleted_cube = fillet(test_cube, [], radius=0.2)
        print(f"âœ“ åœ†è§’æ“ä½œæˆåŠŸ: {filleted_cube}")
        results.append(filleted_cube)
        export_model(filleted_cube, "19_filleted_cube", "åœ†è§’ç«‹æ–¹ä½“")
        
        # æµ‹è¯•å€’è§’æ“ä½œ
        chamfered_cube = chamfer(test_cube, [], distance=0.15)
        print(f"âœ“ å€’è§’æ“ä½œæˆåŠŸ: {chamfered_cube}")
        results.append(chamfered_cube)
        export_model(chamfered_cube, "20_chamfered_cube", "å€’è§’ç«‹æ–¹ä½“")
        
        # æµ‹è¯•æŠ½å£³æ“ä½œ
        hollow_box = shell(test_cube, thickness=0.1, face_tags=["top", "front"])
        print(f"âœ“ æŠ½å£³æ“ä½œæˆåŠŸ: {hollow_box}")
        results.append(hollow_box)
        export_model(hollow_box, "21_hollow_box", "æŠ½å£³ç«‹æ–¹ä½“")
        
        # åˆ›å»ºé«˜çº§æ“ä½œå±•ç¤ºç»„åˆ
        if len(results) >= 3:
            demo_combined = results[0]  # ä»2Dé˜µåˆ—å¼€å§‹
            # åœ¨ä¸åŒä½ç½®æ”¾ç½®å…¶ä»–é«˜çº§æ“ä½œç»“æœ
            with LocalCoordinateSystem(origin=(6, 0, 0), x_axis=(1, 0, 0), y_axis=(0, 1, 0)):
                demo_combined = union(demo_combined, results[2])  # åœ†è§’ç«‹æ–¹ä½“
            with LocalCoordinateSystem(origin=(0, 4, 0), x_axis=(1, 0, 0), y_axis=(0, 1, 0)):
                demo_combined = union(demo_combined, results[3])  # å€’è§’ç«‹æ–¹ä½“
            export_model(demo_combined, "22_advanced_operations_demo", "é«˜çº§æ“ä½œæ¼”ç¤º")
        
        return True
        
    except Exception as e:
        print(f"âœ— é«˜çº§æ“ä½œæµ‹è¯•å¤±è´¥: {e}")
        return False


def test_boolean_operations_comprehensive():
    """å…¨é¢æµ‹è¯•å¸ƒå°”è¿ç®—"""
    print("\n=== å…¨é¢æµ‹è¯•å¸ƒå°”è¿ç®— ===")
    
    results = []
    
    try:
        # åˆ›å»ºæµ‹è¯•å®ä½“
        box1 = make_box(2.0, 2.0, 1.0, center=True)
        box2 = make_box(1.5, 1.5, 1.5, center=True)
        cylinder = make_cylinder(0.6, 2.0)
        
        # å¸ƒå°”å¹¶è¿ç®—
        union_result = union(box1, box2)
        print(f"âœ“ å¸ƒå°”å¹¶è¿ç®—æˆåŠŸ: {union_result}")
        results.append(union_result)
        export_model(union_result, "23_boolean_union", "å¸ƒå°”å¹¶è¿ç®—")
        
        # å¸ƒå°”å‡è¿ç®—
        cut_result = cut(box1, cylinder)
        print(f"âœ“ å¸ƒå°”å‡è¿ç®—æˆåŠŸ: {cut_result}")
        results.append(cut_result)
        export_model(cut_result, "24_boolean_cut", "å¸ƒå°”å‡è¿ç®—")
        
        # å¸ƒå°”äº¤è¿ç®—
        intersect_result = intersect(box1, box2)
        print(f"âœ“ å¸ƒå°”äº¤è¿ç®—æˆåŠŸ: {intersect_result}")
        results.append(intersect_result)
        export_model(intersect_result, "25_boolean_intersect", "å¸ƒå°”äº¤è¿ç®—")
        
        # å¤æ‚å¸ƒå°”è¿ç®—ç»„åˆ
        step1 = union(box1, box2)
        step2 = cut(step1, cylinder)
        print(f"âœ“ å¤æ‚å¸ƒå°”è¿ç®—æˆåŠŸ: {step2}")
        results.append(step2)
        export_model(step2, "26_complex_boolean", "å¤æ‚å¸ƒå°”è¿ç®—")
        
        # åˆ›å»ºå¸ƒå°”è¿ç®—å±•ç¤ºç»„åˆ
        if len(results) >= 4:
            boolean_demo = results[0]  # å¹¶è¿ç®—
            with LocalCoordinateSystem(origin=(4, 0, 0), x_axis=(1, 0, 0), y_axis=(0, 1, 0)):
                boolean_demo = union(boolean_demo, results[1])  # å‡è¿ç®—
            with LocalCoordinateSystem(origin=(0, 4, 0), x_axis=(1, 0, 0), y_axis=(0, 1, 0)):
                boolean_demo = union(boolean_demo, results[2])  # äº¤è¿ç®—
            with LocalCoordinateSystem(origin=(4, 4, 0), x_axis=(1, 0, 0), y_axis=(0, 1, 0)):
                boolean_demo = union(boolean_demo, results[3])  # å¤æ‚è¿ç®—
            export_model(boolean_demo, "27_boolean_operations_showcase", "å¸ƒå°”è¿ç®—å±•ç¤º")
        
        return True
        
    except Exception as e:
        print(f"âœ— å¸ƒå°”è¿ç®—æµ‹è¯•å¤±è´¥: {e}")
        return False


def build_flange():
    """æ„å»ºæ³•å…°é›¶ä»¶ - å¤æ‚é›¶ä»¶ç¤ºä¾‹"""
    print("\n=== æ„å»ºæ³•å…°é›¶ä»¶ ===")
    
    try:
        # æ³•å…°å‚æ•°
        flange_diameter = 6.0      # æ³•å…°å¤–å¾„
        flange_thickness = 0.8     # æ³•å…°åšåº¦
        bore_diameter = 2.0        # ä¸­å¿ƒå­”å¾„
        bolt_circle_diameter = 4.5 # èºæ “å­”åˆ†å¸ƒåœ†ç›´å¾„
        bolt_hole_diameter = 0.4   # èºæ “å­”ç›´å¾„
        num_bolts = 6             # èºæ “å­”æ•°é‡
        
        # 1. åˆ›å»ºæ³•å…°ä¸»ä½“ï¼ˆåœ†ç›˜ï¼‰
        flange_outer = make_cylinder(flange_diameter/2, flange_thickness)
        print("âœ“ æ³•å…°ä¸»ä½“åˆ›å»ºæˆåŠŸ")
        
        # 2. åˆ›å»ºä¸­å¿ƒå­”
        center_hole = make_cylinder(bore_diameter/2, flange_thickness * 1.1)  # ç¨å¾®é•¿ä¸€ç‚¹ç¡®ä¿å®Œå…¨åˆ‡ç©¿
        flange_with_hole = cut(flange_outer, center_hole)
        print("âœ“ ä¸­å¿ƒå­”åŠ å·¥å®Œæˆ")
        
        # 3. åˆ›å»ºèºæ “å­” ä½¿ç”¨é•œåƒé˜µåˆ—
        bolt_circle_diameter /= 2  # è½¬æ¢ä¸ºåŠå¾„
        bolt_hole_radius = bolt_hole_diameter / 2
        with LocalCoordinateSystem(origin=(0, flange_diameter/3, 0),
                                 x_axis=(1, 0, 0), 
                                 y_axis=(0, 1, 0)):
            # åˆ›å»ºèºæ “å­”çš„åœ†æŸ±ä½“
            bolt_hole = make_cylinder(bolt_hole_radius, flange_thickness * 1.1)

        bolt_holes = make_radial_pattern(
            bolt_hole,
            center=Point((0, 0, 0)),  # åœ¨æ³•å…°ä¸­å¿ƒ
            axis=(0, 0, 1),  # Zè½´ä¸ºæ—‹è½¬è½´
            count= num_bolts,
            angle= 2 * math.pi
        )
        
        flange_with_hole = cut(flange_with_hole, bolt_holes)
        flange_result = flange_with_hole
        
        print(f"âœ“ {num_bolts}ä¸ªèºæ “å­”åŠ å·¥å®Œæˆ")
        
        # 4. æ·»åŠ åœ†è§’ï¼ˆå¦‚æœæ”¯æŒï¼‰
        try:
            filleted_flange = fillet(flange_result, [], radius=0.05)
            flange_result = filleted_flange
            print("âœ“ åœ†è§’åŠ å·¥å®Œæˆ")
        except:
            print("âœ“ åœ†è§’åŠ å·¥è·³è¿‡ï¼ˆåŠŸèƒ½é™åˆ¶ï¼‰")
        
        print(f"âœ“ æ³•å…°é›¶ä»¶æ„å»ºå®Œæˆ: {flange_result}")
        
        # å¯¼å‡ºæ³•å…°
        export_model(flange_result, "28_complex_flange", "å¤æ‚æ³•å…°é›¶ä»¶")
        
        return flange_result
        
    except Exception as e:
        print(f"âœ— æ³•å…°æ„å»ºå¤±è´¥: {e}")
        return None


def build_gear_wheel():
    """æ„å»ºç®€åŒ–é½¿è½® - å¦ä¸€ä¸ªå¤æ‚é›¶ä»¶ç¤ºä¾‹"""
    print("\n=== æ„å»ºç®€åŒ–é½¿è½® ===")
    
    try:
        # é½¿è½®å‚æ•°
        outer_radius = 2.0
        inner_radius = 0.3
        thickness = 0.5
        tooth_count = 12
        
        # 1. åˆ›å»ºé½¿è½®ä¸»ä½“
        gear_body = make_cylinder(outer_radius * 0.8, thickness)
        print("âœ“ é½¿è½®ä¸»ä½“åˆ›å»ºæˆåŠŸ")
        
        # 2. åˆ›å»ºä¸­å¿ƒå­”
        center_hole = make_cylinder(inner_radius, thickness * 1.1)
        gear_with_hole = cut(gear_body, center_hole)
        print("âœ“ é½¿è½®ä¸­å¿ƒå­”å®Œæˆ")
        
        # 3. ç®€åŒ–çš„é½¿å½¢ï¼šåœ¨å¤–åœ†å‘¨æ·»åŠ å°ç«‹æ–¹ä½“ä½œä¸ºé½¿
        gear_result = gear_with_hole
        tooth_size = 0.15
        
        for i in range(tooth_count):
            angle = 2 * math.pi * i / tooth_count
            x_offset = (outer_radius * 0.9) * math.cos(angle)
            y_offset = (outer_radius * 0.9) * math.sin(angle)
            
            # ä½¿ç”¨åæ ‡ç³»åˆ›å»ºé½¿
            with LocalCoordinateSystem(origin=(x_offset, y_offset, 0),
                                     x_axis=(math.cos(angle), math.sin(angle), 0),
                                     y_axis=(-math.sin(angle), math.cos(angle), 0)):
                tooth = make_box(tooth_size, tooth_size * 0.5, thickness)
                gear_result = union(gear_result, tooth)
        
        print(f"âœ“ {tooth_count}ä¸ªé½¿åˆ›å»ºå®Œæˆ")
        
        # 4. æ·»åŠ è½®æ¯‚åŠ å¼ºç­‹
        hub_cylinder = make_cylinder(inner_radius * 2, thickness)
        gear_result = union(gear_result, hub_cylinder)
        print("âœ“ è½®æ¯‚åŠ å¼ºå®Œæˆ")
        
        print(f"âœ“ ç®€åŒ–é½¿è½®æ„å»ºå®Œæˆ: {gear_result}")
        
        # å¯¼å‡ºé½¿è½®
        export_model(gear_result, "29_simplified_gear", "ç®€åŒ–é½¿è½®é›¶ä»¶")
        
        return gear_result
        
    except Exception as e:
        print(f"âœ— é½¿è½®æ„å»ºå¤±è´¥: {e}")
        return None


def build_complex_assembly():
    """æ„å»ºå¤æ‚è£…é…ä½“"""
    print("\n=== æ„å»ºå¤æ‚è£…é…ä½“ ===")
    
    try:
        # 1. åˆ›å»ºåº•åº§
        base = make_box(4.0, 4.0, 0.5, center=True)
        
        # 2. åˆ›å»ºç«‹æŸ±
        column = make_cylinder(0.3, 3.0)
        
        # 3. åˆ›å»ºé¡¶æ¿
        with LocalCoordinateSystem(origin=(0, 0, 3.0),
                                 x_axis=(1, 0, 0),
                                 y_axis=(0, 1, 0)):
            top_plate = make_box(2.0, 2.0, 0.3, center=True)
        
        # 4. ç»„è£…
        assembly = union(base, column)
        assembly = union(assembly, top_plate)
        
        # 5. æ·»åŠ è£…é¥°å­”
        for x in [-1, 1]:
            for y in [-1, 1]:
                with LocalCoordinateSystem(origin=(x, y, 0),
                                         x_axis=(1, 0, 0),
                                         y_axis=(0, 1, 0)):
                    deco_hole = make_cylinder(0.1, 0.6)
                    assembly = cut(assembly, deco_hole)
        
        print(f"âœ“ å¤æ‚è£…é…ä½“æ„å»ºå®Œæˆ: {assembly}")
        
        # å¯¼å‡ºè£…é…ä½“
        export_model(assembly, "30_complex_assembly", "å¤æ‚è£…é…ä½“")
        
        return assembly
        
    except Exception as e:
        print(f"âœ— è£…é…ä½“æ„å»ºå¤±è´¥: {e}")
        return None


def test_coordinate_system_complex():
    """æµ‹è¯•å¤æ‚åæ ‡ç³»æ“ä½œ"""
    print("\n=== æµ‹è¯•å¤æ‚åæ ‡ç³»æ“ä½œ ===")
    
    try:
        results = []
        
        # 1. åµŒå¥—åæ ‡ç³»æµ‹è¯•
        with LocalCoordinateSystem(origin=(2, 2, 0),
                                 x_axis=(0, 1, 0),
                                 y_axis=(-1, 0, 0)):
            # å¤–å±‚å±€éƒ¨åæ ‡ç³»
            outer_box = make_box(1, 1, 1)
            results.append(outer_box)
            
            with LocalCoordinateSystem(origin=(1, 1, 0),
                                     x_axis=(1, 0, 0),
                                     y_axis=(0, 1, 0)):
                # å†…å±‚å±€éƒ¨åæ ‡ç³»
                inner_box = make_box(0.5, 0.5, 0.5)
                results.append(inner_box)
        
        # 2. æ—‹è½¬åæ ‡ç³»æµ‹è¯•
        angle = math.pi / 4  # 45åº¦
        with LocalCoordinateSystem(origin=(0, 0, 1),
                                 x_axis=(math.cos(angle), math.sin(angle), 0),
                                 y_axis=(-math.sin(angle), math.cos(angle), 0)):
            rotated_box = make_box(2, 0.5, 0.5)
            results.append(rotated_box)
        
        # 3. æåæ ‡ç³»æ ·å¼çš„å¤šä¸ªä½ç½®
        for i in range(6):
            angle = i * math.pi / 3  # æ¯60åº¦ä¸€ä¸ª
            radius = 3
            x = radius * math.cos(angle)
            y = radius * math.sin(angle)
            
            with LocalCoordinateSystem(origin=(x, y, 0),
                                     x_axis=(math.cos(angle), math.sin(angle), 0),
                                     y_axis=(-math.sin(angle), math.cos(angle), 0)):
                small_box = make_box(0.3, 0.8, 0.3)
                results.append(small_box)
        
        print(f"âœ“ å¤æ‚åæ ‡ç³»æ“ä½œæˆåŠŸï¼Œåˆ›å»ºäº†{len(results)}ä¸ªå®ä½“")
        
        # å¯¼å‡ºä¸ªåˆ«ç»„ä»¶
        if len(results) >= 3:
            export_model(results[0], "31_nested_coordinate_outer", "åµŒå¥—åæ ‡ç³»å¤–å±‚")
            export_model(results[1], "32_nested_coordinate_inner", "åµŒå¥—åæ ‡ç³»å†…å±‚")
            export_model(results[2], "33_rotated_coordinate", "æ—‹è½¬åæ ‡ç³»")
        
        # åˆå¹¶æ‰€æœ‰ç»“æœ
        combined = results[0]
        for result in results[1:]:
            combined = union(combined, result)
        
        print(f"âœ“ åæ ‡ç³»æµ‹è¯•ç»“æœåˆå¹¶: {combined}")
        export_model(combined, "34_coordinate_system_showcase", "åæ ‡ç³»æ“ä½œå±•ç¤º")
        
        return True
        
    except Exception as e:
        print(f"âœ— å¤æ‚åæ ‡ç³»æ“ä½œå¤±è´¥: {e}")
        return False


def test_helical_sweep_operations():
    """æµ‹è¯•èºæ—‹æ‰«æ æ“ä½œ"""
    print("\n=== æµ‹è¯•èºæ—‹æ‰«æ æ“ä½œ ===")
    
    results = []
    
    try:
        # æµ‹è¯•1: åœ†å½¢æˆªé¢èºæ—‹æ‰«æ 
        print("åˆ›å»ºåœ†å½¢æˆªé¢èºæ—‹å¼¹ç°§...")
        
        # åˆ›å»ºåœ†å½¢æˆªé¢profile
        circle_profile = make_circle(radius=0.15)
        
        spring_circle = helical_sweep(
            profile=circle_profile,
            coil_radius=1.0,     # å¼¹ç°§åŠå¾„
            pitch=0.8,           # èºè·
            turns=3.0            # 3åœˆ
        )
        print(f"âœ“ åœ†å½¢æˆªé¢å¼¹ç°§åˆ›å»ºæˆåŠŸ: {spring_circle}")
        results.append(spring_circle)
        export_model(spring_circle, "35_helical_spring_circle", "åœ†å½¢æˆªé¢èºæ—‹å¼¹ç°§")
        
        # æµ‹è¯•2: èºçº¹é½¿å½¢æˆªé¢èºæ—‹æ‰«æ 
        print("åˆ›å»ºèºçº¹é½¿å½¢æˆªé¢èºæ—‹...")
        
        # åˆ›å»ºèºçº¹é½¿å½¢profileï¼ˆæ¢¯å½¢ï¼‰
        thread_points = [
            make_point(0, -0.1, 0),     # åº•éƒ¨å·¦
            make_point(0.2, -0.05, 0),  # é¡¶éƒ¨å·¦  
            make_point(0.2, 0.05, 0),   # é¡¶éƒ¨å³
            make_point(0, 0.1, 0),      # åº•éƒ¨å³
        ]
        
        thread_lines = []
        for i in range(len(thread_points)):
            p1 = thread_points[i]
            p2 = thread_points[(i + 1) % len(thread_points)]
            thread_lines.append(make_line([p1, p2], "segment"))
        
        thread_profile = make_sketch(thread_lines)
        
        spring_thread = helical_sweep(
            profile=thread_profile,
            coil_radius=1.2,     # ç¨å¤§çš„åŠå¾„
            pitch=1.0,           # èºè·
            turns=3.0            # 3åœˆ
        )
        print(f"âœ“ èºçº¹é½¿å½¢å¼¹ç°§åˆ›å»ºæˆåŠŸ: {spring_thread}")
        results.append(spring_thread)
        export_model(spring_thread, "36_helical_spring_thread", "èºçº¹é½¿å½¢èºæ—‹")
        
        # æµ‹è¯•3: ä¸‰è§’å½¢æˆªé¢èºæ—‹æ‰«æ 
        print("åˆ›å»ºä¸‰è§’å½¢æˆªé¢èºæ—‹...")
        
        # åˆ›å»ºä¸‰è§’å½¢profile
        triangle_points = [
            make_point(0, -0.1, 0),     # åº•éƒ¨
            make_point(0.15, 0, 0),     # å³é¡¶ç‚¹
            make_point(0, 0.1, 0),      # é¡¶éƒ¨
        ]
        
        triangle_lines = []
        for i in range(len(triangle_points)):
            p1 = triangle_points[i]
            p2 = triangle_points[(i + 1) % len(triangle_points)]
            triangle_lines.append(make_line([p1, p2], "segment"))
        
        triangle_profile = make_sketch(triangle_lines)
        
        spring_triangle = helical_sweep(
            profile=triangle_profile,
            coil_radius=0.8,     # è¾ƒå°çš„åŠå¾„
            pitch=0.6,           # è¾ƒå°çš„èºè·
            turns=3.0            # 3åœˆ
        )
        print(f"âœ“ ä¸‰è§’å½¢æˆªé¢å¼¹ç°§åˆ›å»ºæˆåŠŸ: {spring_triangle}")
        results.append(spring_triangle)
        export_model(spring_triangle, "37_helical_spring_triangle", "ä¸‰è§’å½¢æˆªé¢èºæ—‹")
        
        # æµ‹è¯•4: é«˜çº§èºæ—‹æ‰«æ ï¼ˆä½¿ç”¨åœ†å½¢profileï¼‰
        try:
            print("åˆ›å»ºé«˜ç²¾åº¦åœ†å½¢æˆªé¢èºæ—‹...")
            
            # ä½¿ç”¨è¾ƒå°çš„åœ†å½¢profile
            fine_circle_profile = make_circle(radius=0.08)
            
            spring_advanced = helical_sweep(
                profile=fine_circle_profile,
                coil_radius=1.4,
                pitch=0.9,
                turns=3.0,
                points_per_turn=20,  # é«˜ç²¾åº¦
                smooth=True
            )
            print(f"âœ“ é«˜ç²¾åº¦èºæ—‹åˆ›å»ºæˆåŠŸ: {spring_advanced}")
            results.append(spring_advanced)
            export_model(spring_advanced, "38_helical_spring_advanced", "é«˜ç²¾åº¦åœ†å½¢æˆªé¢èºæ—‹")
            
        except Exception as e:
            print(f"   âš ï¸ é«˜çº§èºæ—‹æ‰«æ è·³è¿‡: {e}")
        
        # æµ‹è¯•5: åˆ›å»ºèºæ—‹ç»„åˆå±•ç¤º
        print("åˆ›å»ºèºæ—‹ç»„åˆå±•ç¤º...")
        
        if len(results) >= 3:
            try:
                # å°†ä¸åŒçš„èºæ—‹æ”¾åœ¨ä¸åŒä½ç½®
                spiral_combo = results[0]  # åœ†å½¢æˆªé¢åœ¨åŸç‚¹
                
                # èºçº¹é½¿å½¢æ”¾åœ¨å³ä¾§
                with LocalCoordinateSystem(origin=(4, 0, 0), x_axis=(1, 0, 0), y_axis=(0, 1, 0)):
                    spiral_combo = union(spiral_combo, results[1])
                
                # ä¸‰è§’å½¢æˆªé¢æ”¾åœ¨åæ–¹
                with LocalCoordinateSystem(origin=(0, 4, 0), x_axis=(1, 0, 0), y_axis=(0, 1, 0)):
                    spiral_combo = union(spiral_combo, results[2])
                
                # é«˜ç²¾åº¦èºæ—‹æ”¾åœ¨å¯¹è§’ï¼ˆå¦‚æœå­˜åœ¨ï¼‰
                if len(results) >= 4:
                    with LocalCoordinateSystem(origin=(4, 4, 0), x_axis=(1, 0, 0), y_axis=(0, 1, 0)):
                        spiral_combo = union(spiral_combo, results[3])
                
                print(f"âœ“ èºæ—‹ç»„åˆåˆ›å»ºæˆåŠŸ: {spiral_combo}")
                export_model(spiral_combo, "39_helical_spirals_showcase", "èºæ—‹æˆªé¢å±•ç¤ºç»„åˆ")
                
            except Exception as e:
                print(f"   âš ï¸ èºæ—‹ç»„åˆåˆ›å»ºè·³è¿‡: {e}")
        
        print(f"âœ“ èºæ—‹æ‰«æ æ“ä½œæµ‹è¯•å®Œæˆï¼ŒæˆåŠŸåˆ›å»º {len(results)} ä¸ªèºæ—‹æ¨¡å‹")
        print("   æµ‹è¯•çš„profileç±»å‹: åœ†å½¢ã€èºçº¹é½¿å½¢ã€ä¸‰è§’å½¢")
        print("   æ‰€æœ‰èºæ—‹éƒ½æ˜¯3åœˆ")
        
        return True
        
    except Exception as e:
        print(f"âœ— èºæ—‹æ‰«æ æ“ä½œæµ‹è¯•å¤±è´¥: {e}")
        import traceback
        traceback.print_exc()
        return False


def test_coordinate_system_verification():
    """éªŒè¯åæ ‡ç³»è½¬æ¢æ˜¯å¦æ­£ç¡®"""
    print("\n=== éªŒè¯åæ ‡ç³»è½¬æ¢ ===")
    
    try:
        # æµ‹è¯•1: åˆ›å»ºä¸€ä¸ªæ²¿Zè½´çš„ç«‹æ–¹ä½“ï¼ˆåœ¨SimpleCADä¸­åº”è¯¥æ˜¯å‚ç›´çš„ï¼‰
        print("æµ‹è¯•Zè½´ç«‹æ–¹ä½“...")
        z_cube = make_box(0.5, 0.5, 2.0, center=True)  # é«˜åº¦ä¸º2çš„ç«‹æ–¹ä½“
        export_model(z_cube, "42_z_axis_cube", "Zè½´ç«‹æ–¹ä½“")
        
        # æµ‹è¯•2: åˆ›å»ºä¸€ä¸ªæ²¿Zè½´çš„åœ†æŸ±ä½“
        print("æµ‹è¯•Zè½´åœ†æŸ±ä½“...")
        z_cylinder = make_cylinder(0.3, 2.0)  # é«˜åº¦ä¸º2çš„åœ†æŸ±ä½“
        export_model(z_cylinder, "43_z_axis_cylinder", "Zè½´åœ†æŸ±ä½“")
        
        # æµ‹è¯•3: åœ¨ä¸åŒåæ ‡ç³»ä¸­åˆ›å»ºå¯¹è±¡ï¼ŒéªŒè¯å˜æ¢
        print("æµ‹è¯•åæ ‡ç³»å˜æ¢...")
        objects = []
        
        # åŸç‚¹ç«‹æ–¹ä½“
        origin_cube = make_box(0.3, 0.3, 0.3, center=True)
        objects.append(origin_cube)
        
        # Xè½´æ–¹å‘
        with LocalCoordinateSystem(origin=(2, 0, 0), x_axis=(1, 0, 0), y_axis=(0, 1, 0)):
            x_cube = make_box(0.3, 0.3, 0.3, center=True)
            objects.append(x_cube)
        
        # Yè½´æ–¹å‘
        with LocalCoordinateSystem(origin=(0, 2, 0), x_axis=(1, 0, 0), y_axis=(0, 1, 0)):
            y_cube = make_box(0.3, 0.3, 0.3, center=True)
            objects.append(y_cube)
        
        # Zè½´æ–¹å‘
        with LocalCoordinateSystem(origin=(0, 0, 2), x_axis=(1, 0, 0), y_axis=(0, 1, 0)):
            z_cube = make_box(0.3, 0.3, 0.3, center=True)
            objects.append(z_cube)
        
        # åˆå¹¶æ‰€æœ‰ç«‹æ–¹ä½“
        combined = objects[0]
        for obj in objects[1:]:
            combined = union(combined, obj)
        
        export_model(combined, "44_coordinate_verification", "åæ ‡ç³»éªŒè¯")
        
        # æµ‹è¯•4: éªŒè¯æ—‹è½¬æ“ä½œçš„åæ ‡ç³»
        print("æµ‹è¯•æ—‹è½¬åæ ‡ç³»...")
        
        # åˆ›å»ºä¸€ä¸ªçŸ©å½¢ï¼Œç„¶ååœ¨æ—‹è½¬åæ ‡ç³»ä¸­æ”¾ç½®
        base_rect = make_rectangle(1.0, 0.3, center=True)
        base_extruded = extrude(base_rect, distance=0.2)
        
        rotation_objects = [base_extruded]
        
        # 45åº¦æ—‹è½¬
        angle = math.pi / 4
        with LocalCoordinateSystem(origin=(0, 0, 1), 
                                 x_axis=(math.cos(angle), math.sin(angle), 0),
                                 y_axis=(-math.sin(angle), math.cos(angle), 0)):
            rotated_rect = make_rectangle(1.0, 0.3, center=True)
            rotated_extruded = extrude(rotated_rect, distance=0.2)
            rotation_objects.append(rotated_extruded)
        
        # 90åº¦æ—‹è½¬
        angle = math.pi / 2
        with LocalCoordinateSystem(origin=(0, 0, 2), 
                                 x_axis=(math.cos(angle), math.sin(angle), 0),
                                 y_axis=(-math.sin(angle), math.cos(angle), 0)):
            rotated_rect2 = make_rectangle(1.0, 0.3, center=True)
            rotated_extruded2 = extrude(rotated_rect2, distance=0.2)
            rotation_objects.append(rotated_extruded2)
        
        # åˆå¹¶æ—‹è½¬æµ‹è¯•å¯¹è±¡
        rotation_combined = rotation_objects[0]
        for obj in rotation_objects[1:]:
            rotation_combined = union(rotation_combined, obj)
        
        export_model(rotation_combined, "45_rotation_verification", "æ—‹è½¬åæ ‡ç³»éªŒè¯")
        
        print("âœ“ åæ ‡ç³»éªŒè¯æµ‹è¯•å®Œæˆ")
        return True
        
    except Exception as e:
        print(f"âœ— åæ ‡ç³»éªŒè¯æµ‹è¯•å¤±è´¥: {e}")
        import traceback
        traceback.print_exc()
        return False


def run_comprehensive_tests():
    """è¿è¡Œæ‰€æœ‰ç»¼åˆæµ‹è¯•"""
    print("SimpleCAD API ç»¼åˆåŠŸèƒ½æµ‹è¯•")
    print("=" * 60)
    
    test_results = []
    
    # åŸºç¡€å»ºæ¨¡æ“ä½œæµ‹è¯•
    test_results.append(("æ‹‰ä¼¸æ“ä½œ", test_extrude_operations()))
    test_results.append(("æ—‹è½¬æ“ä½œ", test_revolve_operations()))
    test_results.append(("æ”¾æ ·æ“ä½œ", test_loft_operations()))
    test_results.append(("æ‰«æ æ“ä½œ", test_sweep_operations()))
    
    # é«˜çº§æ“ä½œæµ‹è¯•
    test_results.append(("é«˜çº§æ“ä½œ", test_advanced_operations()))
    test_results.append(("å¸ƒå°”è¿ç®—", test_boolean_operations_comprehensive()))
    
    # èºæ—‹æ‰«æ æµ‹è¯•
    test_results.append(("èºæ—‹æ‰«æ ", test_helical_sweep_operations()))
    
    # å¤æ‚é›¶ä»¶æ„å»ºæµ‹è¯•
    flange = build_flange()
    test_results.append(("æ³•å…°æ„å»º", flange is not None))
    
    gear = build_gear_wheel()
    test_results.append(("é½¿è½®æ„å»º", gear is not None))
    
    assembly = build_complex_assembly()
    test_results.append(("è£…é…ä½“æ„å»º", assembly is not None))
    
    # åæ ‡ç³»æµ‹è¯•
    test_results.append(("å¤æ‚åæ ‡ç³»", test_coordinate_system_complex()))
    test_results.append(("åæ ‡ç³»éªŒè¯", test_coordinate_system_verification()))
    test_results.append(("åæ ‡ç³»éªŒè¯", test_coordinate_system_verification()))
    
    # è¾“å‡ºæµ‹è¯•ç»“æœ
    print("\n" + "=" * 60)
    print("æµ‹è¯•ç»“æœæ±‡æ€»:")
    print("=" * 60)
    
    passed = 0
    failed = 0
    
    for test_name, result in test_results:
        status = "âœ“ é€šè¿‡" if result else "âœ— å¤±è´¥"
        print(f"{test_name:<20}: {status}")
        if result:
            passed += 1
        else:
            failed += 1
    
    print("=" * 60)
    print(f"æ€»è®¡: {len(test_results)} é¡¹æµ‹è¯•")
    print(f"é€šè¿‡: {passed} é¡¹")
    print(f"å¤±è´¥: {failed} é¡¹")
    print(f"æˆåŠŸç‡: {passed/len(test_results)*100:.1f}%")
    
    if passed > len(test_results) * 0.8:
        print("ğŸ‰ å¤§éƒ¨åˆ†åŠŸèƒ½æµ‹è¯•é€šè¿‡ï¼APIå®ç°è´¨é‡è‰¯å¥½ã€‚")
    elif passed > len(test_results) * 0.6:
        print("ğŸ‘ å¤šæ•°åŠŸèƒ½æ­£å¸¸ï¼Œéƒ¨åˆ†é«˜çº§åŠŸèƒ½éœ€è¦ä¼˜åŒ–ã€‚")
    else:
        print("âš ï¸ éœ€è¦è¿›ä¸€æ­¥æ”¹è¿›APIå®ç°ã€‚")
    
    return passed, failed


if __name__ == "__main__":
    try:
        passed, failed = run_comprehensive_tests()
        
        print("\n" + "=" * 60)
        print("æµ‹è¯•å®Œæˆï¼")
        print("æŸ¥çœ‹ output/ ç›®å½•ä¸­çš„å¯¼å‡ºæ–‡ä»¶ï¼š")
        print("\n=== åŸºç¡€å»ºæ¨¡æ“ä½œ ===")
        print("- 01_extruded_rectangle.stl (æ‹‰ä¼¸çŸ©å½¢)")
        print("- 02_extruded_circle.stl (æ‹‰ä¼¸åœ†å½¢)")
        print("- 03_directional_extrude.stl (æ–¹å‘æ‹‰ä¼¸)")
        print("- 04_extrude_operations_combined.stl (æ‹‰ä¼¸æ“ä½œç»„åˆ)")
        print("- 05_revolved_l_profile.stl (Lå‹è½®å»“æ—‹è½¬ä½“)")
        print("- 06_half_revolved.stl (180åº¦æ—‹è½¬ä½“)")
        print("- 07_revolve_operations_combined.stl (æ—‹è½¬æ“ä½œç»„åˆ)")
        print("- 08_lofted_rectangles.stl (åˆ†å±‚çŸ©å½¢æ”¾æ ·)")
        print("- 09_circle_to_square_loft.stl (åœ†å½¢åˆ°çŸ©å½¢æ”¾æ ·)")
        print("- 10_complex_loft.stl (å¤æ‚å½¢çŠ¶æ”¾æ ·)")
        print("- 11_loft_operations_combined.stl (æ”¾æ ·æ“ä½œç»„åˆ)")
        print("- 12_straight_sweep.stl (ç›´çº¿æ‰«æ )")
        print("- 13_vertical_sweep.stl (å‚ç›´æ‰«æ )")
        print("- 14_horizontal_sweep.stl (æ°´å¹³æ‰«æ )")
        print("- 15_diagonal_sweep.stl (æ–œå‘æ‰«æ )")
        print("- 16_sweep_operations_combined.stl (æ‰«æ æ“ä½œç»„åˆ)")
        print("\n=== é«˜çº§æ“ä½œ ===")
        print("- 17_linear_array.stl (çº¿æ€§é˜µåˆ—)")
        print("- 18_2d_array.stl (2Dé˜µåˆ—)")
        print("- 19_filleted_cube.stl (åœ†è§’ç«‹æ–¹ä½“)")
        print("- 20_chamfered_cube.stl (å€’è§’ç«‹æ–¹ä½“)")
        print("- 21_hollow_box.stl (æŠ½å£³ç«‹æ–¹ä½“)")
        print("- 22_advanced_operations_demo.stl (é«˜çº§æ“ä½œæ¼”ç¤º)")
        print("\n=== å¸ƒå°”è¿ç®— ===")
        print("- 23_boolean_union.stl (å¸ƒå°”å¹¶è¿ç®—)")
        print("- 24_boolean_cut.stl (å¸ƒå°”å‡è¿ç®—)")
        print("- 25_boolean_intersect.stl (å¸ƒå°”äº¤è¿ç®—)")
        print("- 26_complex_boolean.stl (å¤æ‚å¸ƒå°”è¿ç®—)")
        print("- 27_boolean_operations_showcase.stl (å¸ƒå°”è¿ç®—å±•ç¤º)")
        print("\n=== èºæ—‹æ‰«æ  ===")
        print("- 35_helical_spring_basic.stl (åŸºç¡€èºæ—‹å¼¹ç°§)")
        print("- 36_helical_spring_tight.stl (ç´§å¯†èºæ—‹å¼¹ç°§)")
        print("- 37_helical_spring_heavy.stl (ç²—å¤§èºæ—‹å¼¹ç°§)")
        print("- 38_helical_spring_mini.stl (å°å‹ç²¾å¯†èºæ—‹å¼¹ç°§)")
        print("- 39_helical_spring_advanced.stl (é«˜ç²¾åº¦èºæ—‹å¼¹ç°§)")
        print("- 40_helical_springs_showcase.stl (èºæ—‹å¼¹ç°§å±•ç¤ºç»„åˆ)")
        print("- 41_helical_coil_antenna.stl (èºæ—‹çº¿åœˆå¤©çº¿)")
        print("\n=== å¤æ‚é›¶ä»¶ ===")
        print("- 28_complex_flange.stl/.step (å¤æ‚æ³•å…°é›¶ä»¶)")
        print("- 29_simplified_gear.stl/.step (ç®€åŒ–é½¿è½®é›¶ä»¶)")
        print("- 30_complex_assembly.stl/.step (å¤æ‚è£…é…ä½“)")
        print("\n=== åæ ‡ç³»æ“ä½œ ===")
        print("- 31_nested_coordinate_outer.stl (åµŒå¥—åæ ‡ç³»å¤–å±‚)")
        print("- 32_nested_coordinate_inner.stl (åµŒå¥—åæ ‡ç³»å†…å±‚)")
        print("- 33_rotated_coordinate.stl (æ—‹è½¬åæ ‡ç³»)")
        print("- 34_coordinate_system_showcase.stl (åæ ‡ç³»æ“ä½œå±•ç¤º)")
        print("- 42_z_axis_cube.stl (Zè½´ç«‹æ–¹ä½“)")
        print("- 43_z_axis_cylinder.stl (Zè½´åœ†æŸ±ä½“)")
        print("- 44_coordinate_verification.stl (åæ ‡ç³»éªŒè¯ç»„åˆ)")
        print("- 45_rotation_verification.stl (æ—‹è½¬åæ ‡ç³»éªŒè¯)")
        print("\nğŸ‰ æ€»å…±å¯¼å‡ºäº†45+ä¸ªæµ‹è¯•æ¨¡å‹æ–‡ä»¶ï¼åŒ…å«èºæ—‹æ‰«æ å¼¹ç°§å’Œåæ ‡ç³»ä¿®æ­£éªŒè¯ï¼")
        
        exit_code = 0 if failed == 0 else 1
        sys.exit(exit_code)
        
    except Exception as e:
        print(f"æµ‹è¯•æ‰§è¡Œå‡ºé”™: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
