CREATE OR REPLACE FUNCTION MAP_ACTIVITY_TYPE_EN AS (x) ->
    CASE 
        WHEN x = 1  THEN 'Real Estate Buying & Selling Brokerage'
        WHEN x = 2  THEN 'Real Estate Buying & Selling Brokerage'
        WHEN x = 3  THEN 'Real Estate Leasing Brokerage'
        WHEN x = 5  THEN 'Real Estate Leasing Brokerage'
        WHEN x = 7  THEN 'Brokers of Renting Residential Units on Time-Sharing Bases'
        WHEN x = 9  THEN 'Real Estate Development'
        WHEN x = 11 THEN 'Leasing and Management of Other People Property'
        WHEN x = 12 THEN 'Self Owned Property Leasing and Management Services'
        WHEN x = 13 THEN 'Real Estate Management Supervision Services'
        WHEN x = 14 THEN 'Shopping Mall'
        WHEN x = 16 THEN 'Business Complex'
        WHEN x = 17 THEN 'Renting of Residential Units on Time-Sharing Bases'
        WHEN x = 18 THEN 'Documents Clearing Services'
        WHEN x = 19 THEN 'Real Estate Registration Trustee'
        WHEN x = 21 THEN 'Owner Association Management Services'
        WHEN x = 24 THEN 'Real Estate Mortgage Broker'
        WHEN x = 26 THEN 'Real Estate Valuation Services'
        WHEN x = 29 THEN 'Property Observer'
        WHEN x = 34 THEN 'Real Estate Consultancy'
        WHEN x = 38 THEN 'Shopping Mall'
        WHEN x = 39 THEN 'Real Estate Services Trustee'
    END;

CREATE OR REPLACE FUNCTION MAP_ACTIVITY_TYPE_AR AS (x) ->
    CASE 
        WHEN x = 1  THEN 'شراء الأراضي و العقارات و بيعها'
        WHEN x = 2  THEN 'الوساطه في  بيع العقارات و شرائها'
        WHEN x = 3  THEN 'خدمات تأجير العقارات و ادارتها'
        WHEN x = 5  THEN 'الوساطة في تأجير العقارات'
        WHEN x = 7  THEN 'وسيط تأجير الوحدات السكنية بنظام إقتسام الوقت'
        WHEN x = 9  THEN 'التطوير العقاري'
        WHEN x = 11 THEN 'خدمات تاجير وادارة العقارات للغير'
        WHEN x = 12 THEN 'خدمات تاجير وادارة العقارات الخاصة'
        WHEN x = 13 THEN 'خدمات الإشراف الإداري للعقارات'
        WHEN x = 14 THEN 'مركز تسوق'
        WHEN x = 16 THEN 'مجمع تجاري'
        WHEN x = 17 THEN 'خدمات تاجير الوحدات السكنيه بنظام اقتسام الوقت'
        WHEN x = 18 THEN 'خدمات متابعة المعاملات'
        WHEN x = 19 THEN 'أمين تسجيل عقاري'
        WHEN x = 21 THEN 'خدمات الإشراف الإداري لجمعيات الملاك'
        WHEN x = 24 THEN 'وسيط رهن عقاري'
        WHEN x = 26 THEN 'خدمات تثمين العقارات'
        WHEN x = 29 THEN 'خدمات الكشف على العقارات'
        WHEN x = 34 THEN 'الاستشارات العقارية'
        WHEN x = 38 THEN 'مركز تسوق'
        WHEN x = 39 THEN 'أمين الخدمات العقارية'
    END;