CREATE OR REPLACE FUNCTION MAP_NEAREST_METRO_REVERSE AS (x) ->
	CASE 
		WHEN x = 'ADCB Metro Station'                   THEN 0
		WHEN x = 'Abu Baker Al Siddique Metro Station'  THEN 1
		WHEN x = 'Abu Hail Metro Station'               THEN 2
		WHEN x = 'Airport Free Zone'                    THEN 3
		WHEN x = 'Airport Terminal 1 Metro Station'     THEN 4
		WHEN x = 'Al Fahidi Metro Station'              THEN 5
		WHEN x = 'Al Ghubaiba Metro Station'            THEN 6
		WHEN x = 'Al Jadaf Metro Station'               THEN 7
		WHEN x = 'Al Jafiliya Metro Station'            THEN 8
		WHEN x = 'Al Nahda Metro Station'               THEN 9
		WHEN x = 'Al Qiyadah Metro Station'             THEN 10
		WHEN x = 'Al Qusais Metro Station'              THEN 11
		WHEN x = 'Al Ras Metro Station'                 THEN 12
		WHEN x = 'Al Rigga Metro Station'               THEN 13
		WHEN x = 'Al Sufouh'                            THEN 14
		WHEN x = 'Baniyas Square Metro Station'         THEN 15
		WHEN x = 'Buj Khalifa Dubai Mall Metro Station' THEN 16
		WHEN x = 'Burjuman Metro Station'               THEN 17
		WHEN x = 'Business Bay Metro Station'           THEN 18
		WHEN x = 'Creek Metro Station'                  THEN 19
		WHEN x = 'DANUBE Metro Station'                 THEN 20
		WHEN x = 'Damac Properties'                     THEN 21
		WHEN x = 'Deira City Centre'                    THEN 22
		WHEN x = 'Dubai Internet City'                  THEN 23
		WHEN x = 'Dubai Marina'                         THEN 24
		WHEN x = 'ENERGY Metro Station'                 THEN 25
		WHEN x = 'Emirates Metro Station'               THEN 26
		WHEN x = 'Emirates Towers Metro Station'        THEN 27
		WHEN x = 'Etisalat Metro Station'               THEN 28
		WHEN x = 'Financial Centre'                     THEN 29
		WHEN x = 'First Abu Dhabi Bank Metro Station'   THEN 30
		WHEN x = 'GGICO Metro Station'                  THEN 31
		WHEN x = 'Harbour Tower'                        THEN 32
		WHEN x = 'Healthcare City Metro Station'        THEN 33
		WHEN x = 'Ibn Battuta Metro Station'            THEN 34
		WHEN x = 'Jumeirah Beach Resdency'              THEN 35
		WHEN x = 'Jumeirah Beach Residency'             THEN 36
		WHEN x = 'Jumeirah Lakes Towers'                THEN 37
		WHEN x = 'Knowledge Village'                    THEN 38
		WHEN x = 'Marina Mall Metro Station'            THEN 39
		WHEN x = 'Marina Towers'                        THEN 40
		WHEN x = 'Media City'                           THEN 41
		WHEN x = 'Mina Seyahi'                          THEN 42
		WHEN x = 'Nakheel Metro Station'                THEN 43
		WHEN x = 'Noor Bank Metro Station'              THEN 44
		WHEN x = 'Oud Metha Metro Station'              THEN 45
		WHEN x = 'Palm Deira Metro Stations'            THEN 46
		WHEN x = 'Palm Jumeirah'                        THEN 47
		WHEN x = 'Rashidiya Metro Station'              THEN 48
		WHEN x = 'STADIUM Metro Station'                THEN 49
		WHEN x = 'Salah Al Din Metro Station'           THEN 50
		WHEN x = 'Sharaf Dg Metro Station'              THEN 51
		WHEN x = 'Terminal 3'                           THEN 52
		WHEN x = 'Trade Centre Metro Station'           THEN 53
		WHEN x = 'UAE Exchange Metro Station'           THEN 54
		WHEN x = 'Union Metro Station'                  THEN 55
	END;

CREATE OR REPLACE FUNCTION MAP_NEAREST_METRO_EN AS (x) ->
	CASE 
		WHEN x = 0  THEN 'ADCB Metro Station'
		WHEN x = 1  THEN 'Abu Baker Al Siddique Metro Station'
		WHEN x = 2  THEN 'Abu Hail Metro Station'
		WHEN x = 3  THEN 'Airport Free Zone'
		WHEN x = 4  THEN 'Airport Terminal 1 Metro Station'
		WHEN x = 5  THEN 'Al Fahidi Metro Station'
		WHEN x = 6  THEN 'Al Ghubaiba Metro Station'
		WHEN x = 7  THEN 'Al Jadaf Metro Station'
		WHEN x = 8  THEN 'Al Jafiliya Metro Station'
		WHEN x = 9  THEN 'Al Nahda Metro Station'
		WHEN x = 10 THEN 'Al Qiyadah Metro Station'
		WHEN x = 11 THEN 'Al Qusais Metro Station'
		WHEN x = 12 THEN 'Al Ras Metro Station'
		WHEN x = 13 THEN 'Al Rigga Metro Station'
		WHEN x = 14 THEN 'Al Sufouh'
		WHEN x = 15 THEN 'Baniyas Square Metro Station'
		WHEN x = 16 THEN 'Buj Khalifa Dubai Mall Metro Station'
		WHEN x = 17 THEN 'Burjuman Metro Station'
		WHEN x = 18 THEN 'Business Bay Metro Station'
		WHEN x = 19 THEN 'Creek Metro Station'
		WHEN x = 20 THEN 'DANUBE Metro Station'
		WHEN x = 21 THEN 'Damac Properties'
		WHEN x = 22 THEN 'Deira City Centre'
		WHEN x = 23 THEN 'Dubai Internet City'
		WHEN x = 24 THEN 'Dubai Marina'
		WHEN x = 25 THEN 'ENERGY Metro Station'
		WHEN x = 26 THEN 'Emirates Metro Station'
		WHEN x = 27 THEN 'Emirates Towers Metro Station'
		WHEN x = 28 THEN 'Etisalat Metro Station'
		WHEN x = 29 THEN 'Financial Centre'
		WHEN x = 30 THEN 'First Abu Dhabi Bank Metro Station'
		WHEN x = 31 THEN 'GGICO Metro Station'
		WHEN x = 32 THEN 'Harbour Tower'
		WHEN x = 33 THEN 'Healthcare City Metro Station'
		WHEN x = 34 THEN 'Ibn Battuta Metro Station'
		WHEN x = 35 THEN 'Jumeirah Beach Resdency'
		WHEN x = 36 THEN 'Jumeirah Beach Residency'
		WHEN x = 37 THEN 'Jumeirah Lakes Towers'
		WHEN x = 38 THEN 'Knowledge Village'
		WHEN x = 39 THEN 'Marina Mall Metro Station'
		WHEN x = 40 THEN 'Marina Towers'
		WHEN x = 41 THEN 'Media City'
		WHEN x = 42 THEN 'Mina Seyahi'
		WHEN x = 43 THEN 'Nakheel Metro Station'
		WHEN x = 44 THEN 'Noor Bank Metro Station'
		WHEN x = 45 THEN 'Oud Metha Metro Station'
		WHEN x = 46 THEN 'Palm Deira Metro Stations'
		WHEN x = 47 THEN 'Palm Jumeirah'
		WHEN x = 48 THEN 'Rashidiya Metro Station'
		WHEN x = 49 THEN 'STADIUM Metro Station'
		WHEN x = 50 THEN 'Salah Al Din Metro Station'
		WHEN x = 51 THEN 'Sharaf Dg Metro Station'
		WHEN x = 52 THEN 'Terminal 3'
		WHEN x = 53 THEN 'Trade Centre Metro Station'
		WHEN x = 54 THEN 'UAE Exchange Metro Station'
		WHEN x = 55 THEN 'Union Metro Station'
	END;

CREATE OR REPLACE FUNCTION MAP_NEAREST_METRO_AR AS (x) ->
	CASE 
		WHEN x = 0  THEN 'محطة مترو بنك أبوظبي التجاري'
		WHEN x = 1  THEN 'محطة مترو أبو بكر الصديق'
		WHEN x = 2  THEN 'محطة مترو أبو هيل'
		WHEN x = 3  THEN 'المنطقة الحرة بالمطار'
		WHEN x = 4  THEN 'محطة مترو مبنى المطار رقم 1'
		WHEN x = 5  THEN 'محطة مترو الفهيدي'
		WHEN x = 6  THEN 'محطة مترو الغبيبة'
		WHEN x = 7  THEN 'محطة مترو الجداف'
		WHEN x = 8  THEN 'محطة مترو الجافلية'
		WHEN x = 9  THEN 'محطة مترو النهضة'
		WHEN x = 10 THEN 'محطة مترو القيادة'
		WHEN x = 11 THEN 'محطة مترو القصيص'
		WHEN x = 12 THEN 'محطة مترو الراس'
		WHEN x = 13 THEN 'محطة مترو الرقة'
		WHEN x = 14 THEN 'الصفوح'
		WHEN x = 15 THEN 'محطة مترو ميدان بني ياس'
		WHEN x = 16 THEN 'محطة مترو بوج خليفة دبي مول'
		WHEN x = 17 THEN 'محطة مترو برجمان'
		WHEN x = 18 THEN 'محطة مترو الخليج التجاري'
		WHEN x = 19 THEN 'محطة مترو الخور'
		WHEN x = 20 THEN 'محطة مترو الدانوب'
		WHEN x = 21 THEN 'عقارات داماك'
		WHEN x = 22 THEN 'ديرة سيتي سنتر'
		WHEN x = 23 THEN 'مدينة دبي للإنترنت'
		WHEN x = 24 THEN 'مرسى دبي'
		WHEN x = 25 THEN 'محطة مترو الطاقة'
		WHEN x = 26 THEN 'محطة مترو الامارات'
		WHEN x = 27 THEN 'محطة مترو أبراج الإمارات'
		WHEN x = 28 THEN 'محطة مترو اتصالات'
		WHEN x = 29 THEN 'المركز المالي'
		WHEN x = 30 THEN 'محطة مترو بنك أبوظبي الأول'
		WHEN x = 31 THEN 'محطة مترو جي جي كو'
		WHEN x = 32 THEN 'برج هاربور'
		WHEN x = 33 THEN 'محطة مترو مدينة الرعاية الصحية'
		WHEN x = 34 THEN 'محطة مترو ابن بطوطة'
		WHEN x = 35 THEN 'مساكن شاطئ الجميرا'
		WHEN x = 36 THEN 'مساكن شاطئ جميرا'
		WHEN x = 37 THEN 'أبراج بحيرات جميرا'
		WHEN x = 38 THEN 'قرية المعرفة'
		WHEN x = 39 THEN 'محطة مترو مارينا مول'
		WHEN x = 40 THEN 'ابراج مارينا'
		WHEN x = 41 THEN 'ميديا ??سيتي'
		WHEN x = 42 THEN 'مينا السياحي'
		WHEN x = 43 THEN 'محطة مترو النخيل'
		WHEN x = 44 THEN 'محطة مترو نور بنك'
		WHEN x = 45 THEN 'محطة مترو عود ميثاء'
		WHEN x = 46 THEN 'محطات مترو نخلة ديرة'
		WHEN x = 47 THEN 'نخلة جميرا'
		WHEN x = 48 THEN 'محطة مترو الراشدية'
		WHEN x = 49 THEN 'محطة مترو الاستاد'
		WHEN x = 50 THEN 'محطة مترو صلاح الدين'
		WHEN x = 51 THEN 'محطة مترو شرف دي جي'
		WHEN x = 52 THEN 'الممر 3'
		WHEN x = 53 THEN 'محطة مترو المركز التجاري'
		WHEN x = 54 THEN 'محطة مترو الإمارات العربية المتحدة للصرافة'
		WHEN x = 55 THEN 'محطة مترو الاتحاد'
	END;