# Generated by Django 5.2.3 on 2025-06-25 19:31

import federated_foreign_key.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: list[tuple[str, str]] = []

    operations = [
        migrations.CreateModel(
            name="GenericContentType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project",
                    models.CharField(
                        default=federated_foreign_key.models.get_current_project_name,
                        max_length=100,
                    ),
                ),
                ("app_label", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
            ],
            options={
                "unique_together": {("project", "app_label", "model")},
            },
            managers=[
                ("objects", federated_foreign_key.models.GenericContentTypeManager()),
            ],
        ),
    ]
