INSERT INTO "{dld_database}"."{dld_table}_staging"
SELECT 
    FORMAT_INT("grandparent_property_id") AS "grandparent_property_id",
    FORMAT_INT("parent_property_id") AS "parent_property_id",
	FORMAT_INT("property_id") AS "property_id",
    FORMAT_INT("property_sub_type_id") AS "property_sub_type_id",
	FORMAT_INT("area_id") AS "area_id",
	FORMAT_INT("zone_id") AS "zone_id",
    FORMAT_INT("parcel_id") AS "parcel_id",
    FORMAT_INT("munc_zip_code") AS "munc_zip_code",
	FORMAT_INT("munc_number") AS "munc_number",
	FORMAT_INT("land_number") AS "land_number",
	FORMAT_INT("land_sub_number") AS "land_sub_number",
    FORMAT_INT("land_type_id") AS "land_type_id",
    FORMAT_BOOL("is_free_hold") AS "is_free_hold",
	FORMAT_BOOL("is_lease_hold") AS "is_lease_hold",
	FORMAT_BOOL("is_registered") AS "is_registered",
    FORMAT_VARCHAR("pre_registration_number") AS "pre_registration_number",
	FORMAT_INT("master_project_id") AS "master_project_id",
	FORMAT_VARCHAR("master_project_en") AS "master_project_en",
	FORMAT_VARCHAR("master_project_ar") AS "master_project_ar",
	FORMAT_INT("project_id") AS "project_id",
	FORMAT_VARCHAR("project_name_ar") AS "project_name_ar",
    FORMAT_VARCHAR("project_name_en") AS "project_name_en",
	FORMAT_VARCHAR("building_number") AS "building_number",
	FORMAT_VARCHAR("unit_number") AS "unit_number",
    FORMAT_DATE("creation_date") AS "creation_date",
    FORMAT_VARCHAR("floor") AS "floor",
	FORMAT_VARCHAR("rooms_en") AS "rooms_en",
    FORMAT_FLOAT("actual_area") AS "actual_area",
    FORMAT_FLOAT("common_area") AS "common_area",
    FORMAT_INT("actual_common_area") AS "actual_common_area",
	FORMAT_FLOAT("unit_balcony_area") AS "unit_balcony_area",
	FORMAT_INT("parking_allocation_type") AS "parking_allocation_type",
	FORMAT_VARCHAR("unit_parking_number") AS "unit_parking_number"
FROM url(
    'https://www.dubaipulse.gov.ae/dataset/85462a5b-08dc-4325-9242-676a0de4afc4/resource/7d4deadf-c9bc-47a4-85de-998d0ce38bf3/download/units.csv',
    'CSVWithNames'
);
